package main

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

type enumValue struct {
	goConst string
	wire    int32
	name    string
	msgType string
}

func main() {
	messages, err := readMessageNames("protocol")
	check(err)

	var demo []enumValue
	demo = append(demo, readEnum("protocol/demo.proto", "EDemoCommands", "EDemoCommands", messages, demoMessageType)...)

	var packet []enumValue
	packet = append(packet, readEnum("protocol/networkbasetypes.proto", "NET_Messages", "NET_Messages", messages, netMessageType)...)
	packet = append(packet, readEnum("protocol/netmessages.proto", "SVC_Messages", "SVC_Messages", messages, svcMessageType)...)
	packet = append(packet, readEnum("protocol/netmessages.proto", "Bidirectional_Messages", "Bidirectional_Messages", messages, bidirectionalMessageType)...)

	var user []enumValue
	user = append(user, readEnum("protocol/usermessages.proto", "EBaseUserMessages", "EBaseUserMessages", messages, baseUserMessageType)...)
	user = append(user, readEnum("protocol/citadel_usermessages.proto", "CitadelUserMessageIds", "CitadelUserMessageIds", messages, citadelUserMessageType)...)
	packet = append(packet, user...)
	slices.SortFunc(packet, func(a, b enumValue) int { return int(a.wire - b.wire) })

	var out bytes.Buffer
	out.WriteString("// Code generated by generator/dispatchgen; DO NOT EDIT.\n\n")
	out.WriteString("package s2replay\n\n")
	out.WriteString("import \"github.com/paralin/s2replay/protocol\"\n\n")
	writeDecode(&out, "decodeDemoCommand", demo)
	writeDecode(&out, "decodePacketMessage", packet)
	writeDecode(&out, "decodeUserMessage", user)
	check(os.WriteFile("dispatch_generated.go", out.Bytes(), 0o644))
}

func readMessageNames(dir string) (map[string]bool, error) {
	names := map[string]bool{}
	files, err := filepath.Glob(filepath.Join(dir, "*.pb.go"))
	if err != nil {
		return nil, err
	}
	for _, file := range files {
		b, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		for line := range strings.SplitSeq(string(b), "\n") {
			line = strings.TrimSpace(line)
			if !strings.HasPrefix(line, "type ") || !strings.Contains(line, " struct {") {
				continue
			}
			fields := strings.Fields(line)
			if len(fields) >= 3 {
				names[fields[1]] = true
			}
		}
	}
	return names, nil
}

func readEnum(path string, enumName string, goEnum string, messages map[string]bool, mapType func(string, map[string]bool) string) []enumValue {
	b, err := os.ReadFile(path)
	check(err)

	var vals []enumValue
	inEnum := false
	for raw := range strings.SplitSeq(string(b), "\n") {
		line := strings.TrimSpace(raw)
		switch {
		case line == "enum "+enumName+" {":
			inEnum = true
			continue
		case inEnum && line == "}":
			inEnum = false
			continue
		case !inEnum || line == "" || strings.HasPrefix(line, "//"):
			continue
		}

		name, value, ok := parseEnumValue(line)
		if !ok {
			continue
		}
		msgType := mapType(name, messages)
		if msgType == "" {
			continue
		}
		vals = append(vals, enumValue{
			goConst: goEnum + "_" + name,
			wire:    value,
			name:    name,
			msgType: msgType,
		})
	}
	slices.SortFunc(vals, func(a, b enumValue) int { return int(a.wire - b.wire) })
	return vals
}

func parseEnumValue(line string) (string, int32, bool) {
	beforeOptions, _, _ := strings.Cut(line, "[")
	beforeComment, _, _ := strings.Cut(beforeOptions, "//")
	beforeSemi, _, _ := strings.Cut(beforeComment, ";")
	name, rawValue, ok := strings.Cut(beforeSemi, "=")
	if !ok {
		return "", 0, false
	}
	name = strings.TrimSpace(name)
	n, err := strconv.ParseInt(strings.TrimSpace(rawValue), 10, 32)
	if err != nil {
		return "", 0, false
	}
	return name, int32(n), true
}

func demoMessageType(name string, messages map[string]bool) string {
	switch name {
	case "DEM_Error", "DEM_Max", "DEM_IsCompressed":
		return ""
	case "DEM_SignonPacket":
		return "CDemoPacket"
	}
	return existing("CDemo"+exportName(strings.TrimPrefix(name, "DEM_")), messages)
}

func netMessageType(name string, messages map[string]bool) string {
	return existing("CNETMsg_"+exportName(strings.TrimPrefix(name, "net_")), messages)
}

func svcMessageType(name string, messages map[string]bool) string {
	return existing("CSVCMsg_"+exportName(strings.TrimPrefix(name, "svc_")), messages)
}

func bidirectionalMessageType(name string, messages map[string]bool) string {
	return existing("CBidirMsg_"+exportName(strings.TrimPrefix(name, "bi_")), messages)
}

func baseUserMessageType(name string, messages map[string]bool) string {
	switch name {
	case "UM_MAX_BASE":
		return ""
	}
	return existing("CUserMessage"+exportName(strings.TrimPrefix(name, "UM_")), messages)
}

func citadelUserMessageType(name string, messages map[string]bool) string {
	suffix := exportName(strings.TrimPrefix(name, "k_EUserMsg_"))
	if typ := existing("CCitadelUserMessage_"+suffix, messages); typ != "" {
		return typ
	}
	return existing("CCitadelUserMsg_"+suffix, messages)
}

func existing(name string, messages map[string]bool) string {
	if messages[name] {
		return name
	}
	return ""
}

func exportName(s string) string {
	var out strings.Builder
	upperNext := true
	for _, r := range s {
		if r == '_' {
			out.WriteRune(r)
			upperNext = true
			continue
		}
		if upperNext {
			out.WriteRune(unicode.ToUpper(r))
			upperNext = false
			continue
		}
		out.WriteRune(r)
	}
	return out.String()
}

func writeDecode(out *bytes.Buffer, name string, vals []enumValue) {
	out.WriteString("func " + name + "(kind int32, payload []byte) (decodedMessage, bool, error) {\n")
	out.WriteString("\tswitch kind {\n")
	for _, v := range vals {
		out.WriteString("\tcase int32(protocol." + v.goConst + "):\n")
		out.WriteString("\t\tmsg := &protocol." + v.msgType + "{}\n")
		out.WriteString("\t\tif err := msg.UnmarshalVT(payload); err != nil {\n")
		out.WriteString("\t\t\treturn decodedMessage{}, true, err\n")
		out.WriteString("\t\t}\n")
		out.WriteString("\t\treturn decodedMessage{kind: kind, name: \"" + v.name + "\", msg: msg}, true, nil\n")
	}
	out.WriteString("\tdefault:\n")
	out.WriteString("\t\treturn decodedMessage{}, false, nil\n")
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
