// Code generated by generator/dispatchgen; DO NOT EDIT.

package s2replay

import "github.com/paralin/s2replay/protocol"

func decodeDemoCommand(kind int32, payload []byte) (decodedMessage, bool, error) {
	switch kind {
	case int32(protocol.EDemoCommands_DEM_Stop):
		msg := &protocol.CDemoStop{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_Stop", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_FileHeader):
		msg := &protocol.CDemoFileHeader{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_FileHeader", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_FileInfo):
		msg := &protocol.CDemoFileInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_FileInfo", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_SyncTick):
		msg := &protocol.CDemoSyncTick{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_SyncTick", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_SendTables):
		msg := &protocol.CDemoSendTables{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_SendTables", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_ClassInfo):
		msg := &protocol.CDemoClassInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_ClassInfo", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_StringTables):
		msg := &protocol.CDemoStringTables{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_StringTables", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_Packet):
		msg := &protocol.CDemoPacket{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_Packet", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_SignonPacket):
		msg := &protocol.CDemoPacket{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_SignonPacket", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_ConsoleCmd):
		msg := &protocol.CDemoConsoleCmd{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_ConsoleCmd", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_CustomData):
		msg := &protocol.CDemoCustomData{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_CustomData", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_CustomDataCallbacks):
		msg := &protocol.CDemoCustomDataCallbacks{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_CustomDataCallbacks", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_UserCmd):
		msg := &protocol.CDemoUserCmd{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_UserCmd", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_FullPacket):
		msg := &protocol.CDemoFullPacket{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_FullPacket", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_SaveGame):
		msg := &protocol.CDemoSaveGame{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_SaveGame", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_SpawnGroups):
		msg := &protocol.CDemoSpawnGroups{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_SpawnGroups", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_AnimationData):
		msg := &protocol.CDemoAnimationData{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_AnimationData", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_AnimationHeader):
		msg := &protocol.CDemoAnimationHeader{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_AnimationHeader", msg: msg}, true, nil
	case int32(protocol.EDemoCommands_DEM_Recovery):
		msg := &protocol.CDemoRecovery{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "DEM_Recovery", msg: msg}, true, nil
	default:
		return decodedMessage{}, false, nil
	}
}

func decodePacketMessage(kind int32, payload []byte) (decodedMessage, bool, error) {
	switch kind {
	case int32(protocol.NET_Messages_net_NOP):
		msg := &protocol.CNETMsg_NOP{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_NOP", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SplitScreenUser):
		msg := &protocol.CNETMsg_SplitScreenUser{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SplitScreenUser", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_Tick):
		msg := &protocol.CNETMsg_Tick{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_Tick", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_StringCmd):
		msg := &protocol.CNETMsg_StringCmd{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_StringCmd", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SetConVar):
		msg := &protocol.CNETMsg_SetConVar{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SetConVar", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SignonState):
		msg := &protocol.CNETMsg_SignonState{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SignonState", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SpawnGroup_Load):
		msg := &protocol.CNETMsg_SpawnGroup_Load{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SpawnGroup_Load", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SpawnGroup_ManifestUpdate):
		msg := &protocol.CNETMsg_SpawnGroup_ManifestUpdate{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SpawnGroup_ManifestUpdate", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SpawnGroup_SetCreationTick):
		msg := &protocol.CNETMsg_SpawnGroup_SetCreationTick{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SpawnGroup_SetCreationTick", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SpawnGroup_Unload):
		msg := &protocol.CNETMsg_SpawnGroup_Unload{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SpawnGroup_Unload", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_SpawnGroup_LoadCompleted):
		msg := &protocol.CNETMsg_SpawnGroup_LoadCompleted{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_SpawnGroup_LoadCompleted", msg: msg}, true, nil
	case int32(protocol.NET_Messages_net_DebugOverlay):
		msg := &protocol.CNETMsg_DebugOverlay{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "net_DebugOverlay", msg: msg}, true, nil
	case int32(protocol.Bidirectional_Messages_bi_RebroadcastGameEvent):
		msg := &protocol.CBidirMsg_RebroadcastGameEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "bi_RebroadcastGameEvent", msg: msg}, true, nil
	case int32(protocol.Bidirectional_Messages_bi_RebroadcastSource):
		msg := &protocol.CBidirMsg_RebroadcastSource{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "bi_RebroadcastSource", msg: msg}, true, nil
	case int32(protocol.Bidirectional_Messages_bi_PredictionEvent):
		msg := &protocol.CBidirMsg_PredictionEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "bi_PredictionEvent", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_ServerInfo):
		msg := &protocol.CSVCMsg_ServerInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_ServerInfo", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_FlattenedSerializer):
		msg := &protocol.CSVCMsg_FlattenedSerializer{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_FlattenedSerializer", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_ClassInfo):
		msg := &protocol.CSVCMsg_ClassInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_ClassInfo", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_SetPause):
		msg := &protocol.CSVCMsg_SetPause{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_SetPause", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_CreateStringTable):
		msg := &protocol.CSVCMsg_CreateStringTable{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_CreateStringTable", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_UpdateStringTable):
		msg := &protocol.CSVCMsg_UpdateStringTable{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_UpdateStringTable", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_VoiceInit):
		msg := &protocol.CSVCMsg_VoiceInit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_VoiceInit", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_VoiceData):
		msg := &protocol.CSVCMsg_VoiceData{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_VoiceData", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_Print):
		msg := &protocol.CSVCMsg_Print{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_Print", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_Sounds):
		msg := &protocol.CSVCMsg_Sounds{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_Sounds", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_SetView):
		msg := &protocol.CSVCMsg_SetView{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_SetView", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_ClearAllStringTables):
		msg := &protocol.CSVCMsg_ClearAllStringTables{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_ClearAllStringTables", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_CmdKeyValues):
		msg := &protocol.CSVCMsg_CmdKeyValues{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_CmdKeyValues", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_BSPDecal):
		msg := &protocol.CSVCMsg_BSPDecal{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_BSPDecal", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_SplitScreen):
		msg := &protocol.CSVCMsg_SplitScreen{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_SplitScreen", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_PacketEntities):
		msg := &protocol.CSVCMsg_PacketEntities{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_PacketEntities", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_Prefetch):
		msg := &protocol.CSVCMsg_Prefetch{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_Prefetch", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_Menu):
		msg := &protocol.CSVCMsg_Menu{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_Menu", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_GetCvarValue):
		msg := &protocol.CSVCMsg_GetCvarValue{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_GetCvarValue", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_StopSound):
		msg := &protocol.CSVCMsg_StopSound{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_StopSound", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_PeerList):
		msg := &protocol.CSVCMsg_PeerList{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_PeerList", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_PacketReliable):
		msg := &protocol.CSVCMsg_PacketReliable{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_PacketReliable", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_HLTVStatus):
		msg := &protocol.CSVCMsg_HLTVStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_HLTVStatus", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_ServerSteamID):
		msg := &protocol.CSVCMsg_ServerSteamID{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_ServerSteamID", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_FullFrameSplit):
		msg := &protocol.CSVCMsg_FullFrameSplit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_FullFrameSplit", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_RconServerDetails):
		msg := &protocol.CSVCMsg_RconServerDetails{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_RconServerDetails", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_UserMessage):
		msg := &protocol.CSVCMsg_UserMessage{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_UserMessage", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_Broadcast_Command):
		msg := &protocol.CSVCMsg_Broadcast_Command{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_Broadcast_Command", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_HltvFixupOperatorStatus):
		msg := &protocol.CSVCMsg_HltvFixupOperatorStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_HltvFixupOperatorStatus", msg: msg}, true, nil
	case int32(protocol.SVC_Messages_svc_NextMsgPredicted):
		msg := &protocol.CSVCMsg_NextMsgPredicted{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "svc_NextMsgPredicted", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_AchievementEvent):
		msg := &protocol.CUserMessageAchievementEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AchievementEvent", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaption):
		msg := &protocol.CUserMessageCloseCaption{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaption", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaptionDirect):
		msg := &protocol.CUserMessageCloseCaptionDirect{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaptionDirect", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CurrentTimescale):
		msg := &protocol.CUserMessageCurrentTimescale{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CurrentTimescale", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_DesiredTimescale):
		msg := &protocol.CUserMessageDesiredTimescale{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_DesiredTimescale", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Fade):
		msg := &protocol.CUserMessageFade{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Fade", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_GameTitle):
		msg := &protocol.CUserMessageGameTitle{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_GameTitle", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HudMsg):
		msg := &protocol.CUserMessageHudMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HudMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HudText):
		msg := &protocol.CUserMessageHudText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HudText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ColoredText):
		msg := &protocol.CUserMessageColoredText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ColoredText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestState):
		msg := &protocol.CUserMessageRequestState{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestState", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ResetHUD):
		msg := &protocol.CUserMessageResetHUD{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ResetHUD", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Rumble):
		msg := &protocol.CUserMessageRumble{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Rumble", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayText):
		msg := &protocol.CUserMessageSayText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayText2):
		msg := &protocol.CUserMessageSayText2{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayText2", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayTextChannel):
		msg := &protocol.CUserMessageSayTextChannel{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayTextChannel", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Shake):
		msg := &protocol.CUserMessageShake{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Shake", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ShakeDir):
		msg := &protocol.CUserMessageShakeDir{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ShakeDir", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_WaterShake):
		msg := &protocol.CUserMessageWaterShake{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_WaterShake", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_TextMsg):
		msg := &protocol.CUserMessageTextMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_TextMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ScreenTilt):
		msg := &protocol.CUserMessageScreenTilt{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ScreenTilt", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_VoiceMask):
		msg := &protocol.CUserMessageVoiceMask{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_VoiceMask", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SendAudio):
		msg := &protocol.CUserMessageSendAudio{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SendAudio", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ItemPickup):
		msg := &protocol.CUserMessageItemPickup{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ItemPickup", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_AmmoDenied):
		msg := &protocol.CUserMessageAmmoDenied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AmmoDenied", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ShowMenu):
		msg := &protocol.CUserMessageShowMenu{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ShowMenu", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CreditsMsg):
		msg := &protocol.CUserMessageCreditsMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CreditsMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaptionPlaceholder):
		msg := &protocol.CUserMessageCloseCaptionPlaceholder{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaptionPlaceholder", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CameraTransition):
		msg := &protocol.CUserMessageCameraTransition{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CameraTransition", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_AudioParameter):
		msg := &protocol.CUserMessageAudioParameter{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AudioParameter", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HapticsManagerPulse):
		msg := &protocol.CUserMessageHapticsManagerPulse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HapticsManagerPulse", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HapticsManagerEffect):
		msg := &protocol.CUserMessageHapticsManagerEffect{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HapticsManagerEffect", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_UpdateCssClasses):
		msg := &protocol.CUserMessageUpdateCssClasses{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_UpdateCssClasses", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ServerFrameTime):
		msg := &protocol.CUserMessageServerFrameTime{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ServerFrameTime", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_LagCompensationError):
		msg := &protocol.CUserMessageLagCompensationError{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_LagCompensationError", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestDllStatus):
		msg := &protocol.CUserMessageRequestDllStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestDllStatus", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestUtilAction):
		msg := &protocol.CUserMessageRequestUtilAction{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestUtilAction", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestInventory):
		msg := &protocol.CUserMessageRequestInventory{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestInventory", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestDiagnostic):
		msg := &protocol.CUserMessageRequestDiagnostic{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestDiagnostic", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_Damage):
		msg := &protocol.CCitadelUserMessage_Damage{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_Damage", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MapPing):
		msg := &protocol.CCitadelUserMsg_MapPing{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MapPing", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TeamRewards):
		msg := &protocol.CCitadelUserMsg_TeamRewards{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TeamRewards", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TriggerDamageFlash):
		msg := &protocol.CCitadelUserMsg_TriggerDamageFlash{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TriggerDamageFlash", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilitiesChanged):
		msg := &protocol.CCitadelUserMsg_AbilitiesChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilitiesChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_RecentDamageSummary):
		msg := &protocol.CCitadelUserMsg_RecentDamageSummary{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_RecentDamageSummary", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SpectatorTeamChanged):
		msg := &protocol.CCitadelUserMsg_SpectatorTeamChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SpectatorTeamChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatWheel):
		msg := &protocol.CCitadelUserMsg_ChatWheel{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatWheel", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GoldHistory):
		msg := &protocol.CCitadelUserMsg_GoldHistory{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GoldHistory", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatMsg):
		msg := &protocol.CCitadelUserMsg_ChatMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatMsg", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_QuickResponse):
		msg := &protocol.CCitadelUserMsg_QuickResponse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_QuickResponse", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PostMatchDetails):
		msg := &protocol.CCitadelUserMsg_PostMatchDetails{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PostMatchDetails", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatEvent):
		msg := &protocol.CCitadelUserMsg_ChatEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityInterrupted):
		msg := &protocol.CCitadelUserMsg_AbilityInterrupted{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityInterrupted", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_HeroKilled):
		msg := &protocol.CCitadelUserMsg_HeroKilled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_HeroKilled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ReturnIdol):
		msg := &protocol.CCitadelUserMsg_ReturnIdol{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ReturnIdol", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SetClientCameraAngles):
		msg := &protocol.CCitadelUserMsg_SetClientCameraAngles{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SetClientCameraAngles", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MapLine):
		msg := &protocol.CCitadelUserMsg_MapLine{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MapLine", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BulletHit):
		msg := &protocol.CCitadelUserMessage_BulletHit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BulletHit", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ObjectiveMask):
		msg := &protocol.CCitadelUserMessage_ObjectiveMask{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ObjectiveMask", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ModifierApplied):
		msg := &protocol.CCitadelUserMessage_ModifierApplied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ModifierApplied", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CameraController):
		msg := &protocol.CCitadelUserMsg_CameraController{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CameraController", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AuraModifierApplied):
		msg := &protocol.CCitadelUserMessage_AuraModifierApplied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AuraModifierApplied", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ObstructedShotFired):
		msg := &protocol.CCitadelUserMsg_ObstructedShotFired{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ObstructedShotFired", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityLateFailure):
		msg := &protocol.CCitadelUserMsg_AbilityLateFailure{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityLateFailure", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityPing):
		msg := &protocol.CCitadelUserMsg_AbilityPing{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityPing", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PostProcessingAnim):
		msg := &protocol.CCitadelUserMsg_PostProcessingAnim{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PostProcessingAnim", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_DeathReplayData):
		msg := &protocol.CCitadelUserMsg_DeathReplayData{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_DeathReplayData", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PlayerLifetimeStatInfo):
		msg := &protocol.CCitadelUserMsg_PlayerLifetimeStatInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PlayerLifetimeStatInfo", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ForceShopClosed):
		msg := &protocol.CCitadelUserMsg_ForceShopClosed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ForceShopClosed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_StaminaConsumed):
		msg := &protocol.CCitadelUserMsg_StaminaConsumed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_StaminaConsumed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityNotify):
		msg := &protocol.CCitadelUserMessage_AbilityNotify{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityNotify", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GetDamageStatsResponse):
		msg := &protocol.CCitadelUserMsg_GetDamageStatsResponse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GetDamageStatsResponse", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStartSoundEvent):
		msg := &protocol.CCitadelUserMsg_ParticipantStartSoundEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStartSoundEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStopSoundEvent):
		msg := &protocol.CCitadelUserMsg_ParticipantStopSoundEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStopSoundEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStopSoundEventHash):
		msg := &protocol.CCitadelUserMsg_ParticipantStopSoundEventHash{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStopSoundEventHash", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantSetSoundEventParams):
		msg := &protocol.CCitadelUserMsg_ParticipantSetSoundEventParams{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantSetSoundEventParams", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantSetLibraryStackFields):
		msg := &protocol.CCitadelUserMsg_ParticipantSetLibraryStackFields{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantSetLibraryStackFields", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CurrencyChanged):
		msg := &protocol.CCitadelUserMessage_CurrencyChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CurrencyChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GameOver):
		msg := &protocol.CCitadelUserMessage_GameOver{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GameOver", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BossKilled):
		msg := &protocol.CCitadelUserMsg_BossKilled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BossKilled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BossDamaged):
		msg := &protocol.CCitadelUserMsg_BossDamaged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BossDamaged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MidBossSpawned):
		msg := &protocol.CCitadelUserMsg_MidBossSpawned{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MidBossSpawned", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_RejuvStatus):
		msg := &protocol.CCitadelUserMsg_RejuvStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_RejuvStatus", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_KillStreak):
		msg := &protocol.CCitadelUserMsg_KillStreak{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_KillStreak", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TeamMsg):
		msg := &protocol.CCitadelUserMsg_TeamMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TeamMsg", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PlayerRespawned):
		msg := &protocol.CCitadelUserMsg_PlayerRespawned{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PlayerRespawned", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CallCheaterVote):
		msg := &protocol.CCitadelUserMsg_CallCheaterVote{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CallCheaterVote", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MeleeHit):
		msg := &protocol.CCitadelUserMessage_MeleeHit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MeleeHit", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_FlexSlotUnlocked):
		msg := &protocol.CCitadelUserMsg_FlexSlotUnlocked{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_FlexSlotUnlocked", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SeasonalKill):
		msg := &protocol.CCitadelUserMsg_SeasonalKill{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SeasonalKill", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AG2ParamTrigger):
		msg := &protocol.CCitadelUserMsg_AG2ParamTrigger{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AG2ParamTrigger", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ItemPurchaseNotification):
		msg := &protocol.CCitadelUserMessage_ItemPurchaseNotification{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ItemPurchaseNotification", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_EntityPortalled):
		msg := &protocol.CCitadelUserMsg_EntityPortalled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_EntityPortalled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_StreetBrawlScoring):
		msg := &protocol.CCitadelUserMsg_StreetBrawlScoring{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_StreetBrawlScoring", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_HudGameAnnouncement):
		msg := &protocol.CCitadelUserMsg_HudGameAnnouncement{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_HudGameAnnouncement", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ItemDraftReaction):
		msg := &protocol.CCitadelUserMsg_ItemDraftReaction{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ItemDraftReaction", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ImportantAbilityUsed):
		msg := &protocol.CCitadelUserMessage_ImportantAbilityUsed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ImportantAbilityUsed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BannedHeroes):
		msg := &protocol.CCitadelUserMsg_BannedHeroes{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BannedHeroes", msg: msg}, true, nil
	default:
		return decodedMessage{}, false, nil
	}
}

func decodeUserMessage(kind int32, payload []byte) (decodedMessage, bool, error) {
	switch kind {
	case int32(protocol.EBaseUserMessages_UM_AchievementEvent):
		msg := &protocol.CUserMessageAchievementEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AchievementEvent", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaption):
		msg := &protocol.CUserMessageCloseCaption{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaption", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaptionDirect):
		msg := &protocol.CUserMessageCloseCaptionDirect{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaptionDirect", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CurrentTimescale):
		msg := &protocol.CUserMessageCurrentTimescale{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CurrentTimescale", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_DesiredTimescale):
		msg := &protocol.CUserMessageDesiredTimescale{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_DesiredTimescale", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Fade):
		msg := &protocol.CUserMessageFade{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Fade", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_GameTitle):
		msg := &protocol.CUserMessageGameTitle{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_GameTitle", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HudMsg):
		msg := &protocol.CUserMessageHudMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HudMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HudText):
		msg := &protocol.CUserMessageHudText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HudText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ColoredText):
		msg := &protocol.CUserMessageColoredText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ColoredText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestState):
		msg := &protocol.CUserMessageRequestState{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestState", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ResetHUD):
		msg := &protocol.CUserMessageResetHUD{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ResetHUD", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Rumble):
		msg := &protocol.CUserMessageRumble{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Rumble", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayText):
		msg := &protocol.CUserMessageSayText{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayText", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayText2):
		msg := &protocol.CUserMessageSayText2{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayText2", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SayTextChannel):
		msg := &protocol.CUserMessageSayTextChannel{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SayTextChannel", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_Shake):
		msg := &protocol.CUserMessageShake{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_Shake", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ShakeDir):
		msg := &protocol.CUserMessageShakeDir{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ShakeDir", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_WaterShake):
		msg := &protocol.CUserMessageWaterShake{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_WaterShake", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_TextMsg):
		msg := &protocol.CUserMessageTextMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_TextMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ScreenTilt):
		msg := &protocol.CUserMessageScreenTilt{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ScreenTilt", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_VoiceMask):
		msg := &protocol.CUserMessageVoiceMask{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_VoiceMask", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_SendAudio):
		msg := &protocol.CUserMessageSendAudio{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_SendAudio", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ItemPickup):
		msg := &protocol.CUserMessageItemPickup{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ItemPickup", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_AmmoDenied):
		msg := &protocol.CUserMessageAmmoDenied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AmmoDenied", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ShowMenu):
		msg := &protocol.CUserMessageShowMenu{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ShowMenu", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CreditsMsg):
		msg := &protocol.CUserMessageCreditsMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CreditsMsg", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CloseCaptionPlaceholder):
		msg := &protocol.CUserMessageCloseCaptionPlaceholder{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CloseCaptionPlaceholder", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_CameraTransition):
		msg := &protocol.CUserMessageCameraTransition{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_CameraTransition", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_AudioParameter):
		msg := &protocol.CUserMessageAudioParameter{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_AudioParameter", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HapticsManagerPulse):
		msg := &protocol.CUserMessageHapticsManagerPulse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HapticsManagerPulse", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_HapticsManagerEffect):
		msg := &protocol.CUserMessageHapticsManagerEffect{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_HapticsManagerEffect", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_UpdateCssClasses):
		msg := &protocol.CUserMessageUpdateCssClasses{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_UpdateCssClasses", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_ServerFrameTime):
		msg := &protocol.CUserMessageServerFrameTime{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_ServerFrameTime", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_LagCompensationError):
		msg := &protocol.CUserMessageLagCompensationError{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_LagCompensationError", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestDllStatus):
		msg := &protocol.CUserMessageRequestDllStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestDllStatus", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestUtilAction):
		msg := &protocol.CUserMessageRequestUtilAction{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestUtilAction", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestInventory):
		msg := &protocol.CUserMessageRequestInventory{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestInventory", msg: msg}, true, nil
	case int32(protocol.EBaseUserMessages_UM_RequestDiagnostic):
		msg := &protocol.CUserMessageRequestDiagnostic{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "UM_RequestDiagnostic", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_Damage):
		msg := &protocol.CCitadelUserMessage_Damage{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_Damage", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MapPing):
		msg := &protocol.CCitadelUserMsg_MapPing{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MapPing", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TeamRewards):
		msg := &protocol.CCitadelUserMsg_TeamRewards{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TeamRewards", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TriggerDamageFlash):
		msg := &protocol.CCitadelUserMsg_TriggerDamageFlash{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TriggerDamageFlash", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilitiesChanged):
		msg := &protocol.CCitadelUserMsg_AbilitiesChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilitiesChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_RecentDamageSummary):
		msg := &protocol.CCitadelUserMsg_RecentDamageSummary{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_RecentDamageSummary", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SpectatorTeamChanged):
		msg := &protocol.CCitadelUserMsg_SpectatorTeamChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SpectatorTeamChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatWheel):
		msg := &protocol.CCitadelUserMsg_ChatWheel{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatWheel", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GoldHistory):
		msg := &protocol.CCitadelUserMsg_GoldHistory{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GoldHistory", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatMsg):
		msg := &protocol.CCitadelUserMsg_ChatMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatMsg", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_QuickResponse):
		msg := &protocol.CCitadelUserMsg_QuickResponse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_QuickResponse", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PostMatchDetails):
		msg := &protocol.CCitadelUserMsg_PostMatchDetails{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PostMatchDetails", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ChatEvent):
		msg := &protocol.CCitadelUserMsg_ChatEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ChatEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityInterrupted):
		msg := &protocol.CCitadelUserMsg_AbilityInterrupted{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityInterrupted", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_HeroKilled):
		msg := &protocol.CCitadelUserMsg_HeroKilled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_HeroKilled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ReturnIdol):
		msg := &protocol.CCitadelUserMsg_ReturnIdol{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ReturnIdol", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SetClientCameraAngles):
		msg := &protocol.CCitadelUserMsg_SetClientCameraAngles{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SetClientCameraAngles", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MapLine):
		msg := &protocol.CCitadelUserMsg_MapLine{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MapLine", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BulletHit):
		msg := &protocol.CCitadelUserMessage_BulletHit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BulletHit", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ObjectiveMask):
		msg := &protocol.CCitadelUserMessage_ObjectiveMask{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ObjectiveMask", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ModifierApplied):
		msg := &protocol.CCitadelUserMessage_ModifierApplied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ModifierApplied", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CameraController):
		msg := &protocol.CCitadelUserMsg_CameraController{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CameraController", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AuraModifierApplied):
		msg := &protocol.CCitadelUserMessage_AuraModifierApplied{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AuraModifierApplied", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ObstructedShotFired):
		msg := &protocol.CCitadelUserMsg_ObstructedShotFired{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ObstructedShotFired", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityLateFailure):
		msg := &protocol.CCitadelUserMsg_AbilityLateFailure{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityLateFailure", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityPing):
		msg := &protocol.CCitadelUserMsg_AbilityPing{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityPing", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PostProcessingAnim):
		msg := &protocol.CCitadelUserMsg_PostProcessingAnim{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PostProcessingAnim", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_DeathReplayData):
		msg := &protocol.CCitadelUserMsg_DeathReplayData{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_DeathReplayData", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PlayerLifetimeStatInfo):
		msg := &protocol.CCitadelUserMsg_PlayerLifetimeStatInfo{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PlayerLifetimeStatInfo", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ForceShopClosed):
		msg := &protocol.CCitadelUserMsg_ForceShopClosed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ForceShopClosed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_StaminaConsumed):
		msg := &protocol.CCitadelUserMsg_StaminaConsumed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_StaminaConsumed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AbilityNotify):
		msg := &protocol.CCitadelUserMessage_AbilityNotify{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AbilityNotify", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GetDamageStatsResponse):
		msg := &protocol.CCitadelUserMsg_GetDamageStatsResponse{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GetDamageStatsResponse", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStartSoundEvent):
		msg := &protocol.CCitadelUserMsg_ParticipantStartSoundEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStartSoundEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStopSoundEvent):
		msg := &protocol.CCitadelUserMsg_ParticipantStopSoundEvent{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStopSoundEvent", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantStopSoundEventHash):
		msg := &protocol.CCitadelUserMsg_ParticipantStopSoundEventHash{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantStopSoundEventHash", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantSetSoundEventParams):
		msg := &protocol.CCitadelUserMsg_ParticipantSetSoundEventParams{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantSetSoundEventParams", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ParticipantSetLibraryStackFields):
		msg := &protocol.CCitadelUserMsg_ParticipantSetLibraryStackFields{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ParticipantSetLibraryStackFields", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CurrencyChanged):
		msg := &protocol.CCitadelUserMessage_CurrencyChanged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CurrencyChanged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_GameOver):
		msg := &protocol.CCitadelUserMessage_GameOver{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_GameOver", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BossKilled):
		msg := &protocol.CCitadelUserMsg_BossKilled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BossKilled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BossDamaged):
		msg := &protocol.CCitadelUserMsg_BossDamaged{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BossDamaged", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MidBossSpawned):
		msg := &protocol.CCitadelUserMsg_MidBossSpawned{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MidBossSpawned", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_RejuvStatus):
		msg := &protocol.CCitadelUserMsg_RejuvStatus{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_RejuvStatus", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_KillStreak):
		msg := &protocol.CCitadelUserMsg_KillStreak{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_KillStreak", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_TeamMsg):
		msg := &protocol.CCitadelUserMsg_TeamMsg{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_TeamMsg", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_PlayerRespawned):
		msg := &protocol.CCitadelUserMsg_PlayerRespawned{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_PlayerRespawned", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_CallCheaterVote):
		msg := &protocol.CCitadelUserMsg_CallCheaterVote{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_CallCheaterVote", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_MeleeHit):
		msg := &protocol.CCitadelUserMessage_MeleeHit{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_MeleeHit", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_FlexSlotUnlocked):
		msg := &protocol.CCitadelUserMsg_FlexSlotUnlocked{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_FlexSlotUnlocked", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_SeasonalKill):
		msg := &protocol.CCitadelUserMsg_SeasonalKill{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_SeasonalKill", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_AG2ParamTrigger):
		msg := &protocol.CCitadelUserMsg_AG2ParamTrigger{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_AG2ParamTrigger", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ItemPurchaseNotification):
		msg := &protocol.CCitadelUserMessage_ItemPurchaseNotification{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ItemPurchaseNotification", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_EntityPortalled):
		msg := &protocol.CCitadelUserMsg_EntityPortalled{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_EntityPortalled", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_StreetBrawlScoring):
		msg := &protocol.CCitadelUserMsg_StreetBrawlScoring{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_StreetBrawlScoring", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_HudGameAnnouncement):
		msg := &protocol.CCitadelUserMsg_HudGameAnnouncement{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_HudGameAnnouncement", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ItemDraftReaction):
		msg := &protocol.CCitadelUserMsg_ItemDraftReaction{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ItemDraftReaction", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_ImportantAbilityUsed):
		msg := &protocol.CCitadelUserMessage_ImportantAbilityUsed{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_ImportantAbilityUsed", msg: msg}, true, nil
	case int32(protocol.CitadelUserMessageIds_k_EUserMsg_BannedHeroes):
		msg := &protocol.CCitadelUserMsg_BannedHeroes{}
		if err := msg.UnmarshalVT(payload); err != nil {
			return decodedMessage{}, true, err
		}
		return decodedMessage{kind: kind, name: "k_EUserMsg_BannedHeroes", msg: msg}, true, nil
	default:
		return decodedMessage{}, false, nil
	}
}

