// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.14.0
// source: github.com/paralin/s2replay/protocol/base_modifier.proto

package protocol

import (
	binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
)

type MODIFIER_ENTRY_TYPE int32

const (
	MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_ACTIVE  MODIFIER_ENTRY_TYPE = 1
	MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_REMOVED MODIFIER_ENTRY_TYPE = 2
)

// Enum value maps for MODIFIER_ENTRY_TYPE.
var (
	MODIFIER_ENTRY_TYPE_name = map[int32]string{
		1: "MODIFIER_ENTRY_TYPE_ACTIVE",
		2: "MODIFIER_ENTRY_TYPE_REMOVED",
	}
	MODIFIER_ENTRY_TYPE_value = map[string]int32{
		"MODIFIER_ENTRY_TYPE_ACTIVE":  1,
		"MODIFIER_ENTRY_TYPE_REMOVED": 2,
	}
)

func (x MODIFIER_ENTRY_TYPE) Enum() *MODIFIER_ENTRY_TYPE {
	p := new(MODIFIER_ENTRY_TYPE)
	*p = x
	return p
}

func (x MODIFIER_ENTRY_TYPE) String() string {
	name, valid := MODIFIER_ENTRY_TYPE_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

type CModifierTableEntry struct {
	unknownFields            []byte
	EntryType                *MODIFIER_ENTRY_TYPE `protobuf:"varint,1,opt,name=entry_type,json=entryType,def=1" json:"entryType,omitempty"`
	Parent                   *uint32              `protobuf:"varint,2,opt,name=parent,def=16777215" json:"parent,omitempty"`
	SerialNumber             *uint32              `protobuf:"varint,3,opt,name=serial_number,json=serialNumber" json:"serialNumber,omitempty"`
	ModifierSubclass         *uint32              `protobuf:"varint,4,opt,name=modifier_subclass,json=modifierSubclass,def=0" json:"modifierSubclass,omitempty"`
	StackCount               *int32               `protobuf:"varint,5,opt,name=stack_count,json=stackCount" json:"stackCount,omitempty"`
	MaxStackCount            *int32               `protobuf:"varint,6,opt,name=max_stack_count,json=maxStackCount" json:"maxStackCount,omitempty"`
	LastAppliedTime          *float32             `protobuf:"fixed32,7,opt,name=last_applied_time,json=lastAppliedTime" json:"lastAppliedTime,omitempty"`
	Duration                 *float32             `protobuf:"fixed32,8,opt,name=duration,def=-1" json:"duration,omitempty"`
	Caster                   *uint32              `protobuf:"varint,9,opt,name=caster,def=16777215" json:"caster,omitempty"`
	Ability                  *uint32              `protobuf:"varint,10,opt,name=ability,def=16777215" json:"ability,omitempty"`
	AuraProviderSerialNumber *int32               `protobuf:"varint,11,opt,name=aura_provider_serial_number,json=auraProviderSerialNumber" json:"auraProviderSerialNumber,omitempty"`
	AuraProviderEhandle      *uint32              `protobuf:"varint,12,opt,name=aura_provider_ehandle,json=auraProviderEhandle,def=16777215" json:"auraProviderEhandle,omitempty"`
	AbilitySubclass          *uint32              `protobuf:"varint,13,opt,name=ability_subclass,json=abilitySubclass,def=0" json:"abilitySubclass,omitempty"`
	InAuraRange              *bool                `protobuf:"varint,14,opt,name=in_aura_range,json=inAuraRange" json:"inAuraRange,omitempty"`
	Bool1_                   *bool                `protobuf:"varint,20,opt,name=bool1_,json=bool1" json:"bool1,omitempty"`
	Bool2_                   *bool                `protobuf:"varint,21,opt,name=bool2_,json=bool2" json:"bool2,omitempty"`
	Bool3_                   *bool                `protobuf:"varint,22,opt,name=bool3_,json=bool3" json:"bool3,omitempty"`
	Bool4_                   *bool                `protobuf:"varint,23,opt,name=bool4_,json=bool4" json:"bool4,omitempty"`
	Int1_                    *int32               `protobuf:"varint,25,opt,name=int1_,json=int1" json:"int1,omitempty"`
	Int2_                    *int32               `protobuf:"varint,26,opt,name=int2_,json=int2" json:"int2,omitempty"`
	Int3_                    *int32               `protobuf:"varint,27,opt,name=int3_,json=int3" json:"int3,omitempty"`
	Int4_                    *int32               `protobuf:"varint,28,opt,name=int4_,json=int4" json:"int4,omitempty"`
	Float1_                  *float32             `protobuf:"fixed32,30,opt,name=float1_,json=float1" json:"float1,omitempty"`
	Float2_                  *float32             `protobuf:"fixed32,31,opt,name=float2_,json=float2" json:"float2,omitempty"`
	Float3_                  *float32             `protobuf:"fixed32,32,opt,name=float3_,json=float3" json:"float3,omitempty"`
	Float4_                  *float32             `protobuf:"fixed32,33,opt,name=float4_,json=float4" json:"float4,omitempty"`
	Float5_                  *float32             `protobuf:"fixed32,49,opt,name=float5_,json=float5" json:"float5,omitempty"`
	Float6_                  *float32             `protobuf:"fixed32,50,opt,name=float6_,json=float6" json:"float6,omitempty"`
	Float7_                  *float32             `protobuf:"fixed32,51,opt,name=float7_,json=float7" json:"float7,omitempty"`
	Float8_                  *float32             `protobuf:"fixed32,52,opt,name=float8_,json=float8" json:"float8,omitempty"`
	Float9_                  *float32             `protobuf:"fixed32,53,opt,name=float9_,json=float9" json:"float9,omitempty"`
	Float10_                 *float32             `protobuf:"fixed32,54,opt,name=float10_,json=float10" json:"float10,omitempty"`
	Float11_                 *float32             `protobuf:"fixed32,55,opt,name=float11_,json=float11" json:"float11,omitempty"`
	Float12_                 *float32             `protobuf:"fixed32,56,opt,name=float12_,json=float12" json:"float12,omitempty"`
	Float13_                 *float32             `protobuf:"fixed32,57,opt,name=float13_,json=float13" json:"float13,omitempty"`
	Float14_                 *float32             `protobuf:"fixed32,58,opt,name=float14_,json=float14" json:"float14,omitempty"`
	Float15_                 *float32             `protobuf:"fixed32,59,opt,name=float15_,json=float15" json:"float15,omitempty"`
	Float16_                 *float32             `protobuf:"fixed32,60,opt,name=float16_,json=float16" json:"float16,omitempty"`
	Uint1_                   *uint64              `protobuf:"varint,35,opt,name=uint1_,json=uint1" json:"uint1,omitempty"`
	Uint2_                   *uint64              `protobuf:"varint,36,opt,name=uint2_,json=uint2" json:"uint2,omitempty"`
	Uint3_                   *uint64              `protobuf:"varint,37,opt,name=uint3_,json=uint3" json:"uint3,omitempty"`
	Uint4_                   *uint64              `protobuf:"varint,38,opt,name=uint4_,json=uint4" json:"uint4,omitempty"`
	Vec1_                    *CMsgVector          `protobuf:"bytes,40,opt,name=vec1_,json=vec1" json:"vec1,omitempty"`
	Vec2_                    *CMsgVector          `protobuf:"bytes,41,opt,name=vec2_,json=vec2" json:"vec2,omitempty"`
	Vec3_                    *CMsgVector          `protobuf:"bytes,42,opt,name=vec3_,json=vec3" json:"vec3,omitempty"`
	Vec4_                    *CMsgVector          `protobuf:"bytes,43,opt,name=vec4_,json=vec4" json:"vec4,omitempty"`
	String1_                 *string              `protobuf:"bytes,45,opt,name=string1_,json=string1" json:"string1,omitempty"`
	String2_                 *string              `protobuf:"bytes,46,opt,name=string2_,json=string2" json:"string2,omitempty"`
	String3_                 *string              `protobuf:"bytes,47,opt,name=string3_,json=string3" json:"string3,omitempty"`
	String4_                 *string              `protobuf:"bytes,48,opt,name=string4_,json=string4" json:"string4,omitempty"`
}

// Default values for CModifierTableEntry fields.
const (
	Default_CModifierTableEntry_EntryType           = MODIFIER_ENTRY_TYPE_MODIFIER_ENTRY_TYPE_ACTIVE
	Default_CModifierTableEntry_Parent              = uint32(16777215)
	Default_CModifierTableEntry_ModifierSubclass    = uint32(0)
	Default_CModifierTableEntry_Duration            = float32(-1)
	Default_CModifierTableEntry_Caster              = uint32(16777215)
	Default_CModifierTableEntry_Ability             = uint32(16777215)
	Default_CModifierTableEntry_AuraProviderEhandle = uint32(16777215)
	Default_CModifierTableEntry_AbilitySubclass     = uint32(0)
)

func (x *CModifierTableEntry) Reset() {
	*x = CModifierTableEntry{}
}

func (*CModifierTableEntry) ProtoMessage() {}

func (x *CModifierTableEntry) GetEntryType() MODIFIER_ENTRY_TYPE {
	if x != nil && x.EntryType != nil {
		return *x.EntryType
	}
	return Default_CModifierTableEntry_EntryType
}

func (x *CModifierTableEntry) GetParent() uint32 {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return Default_CModifierTableEntry_Parent
}

func (x *CModifierTableEntry) GetSerialNumber() uint32 {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return 0
}

func (x *CModifierTableEntry) GetModifierSubclass() uint32 {
	if x != nil && x.ModifierSubclass != nil {
		return *x.ModifierSubclass
	}
	return Default_CModifierTableEntry_ModifierSubclass
}

func (x *CModifierTableEntry) GetStackCount() int32 {
	if x != nil && x.StackCount != nil {
		return *x.StackCount
	}
	return 0
}

func (x *CModifierTableEntry) GetMaxStackCount() int32 {
	if x != nil && x.MaxStackCount != nil {
		return *x.MaxStackCount
	}
	return 0
}

func (x *CModifierTableEntry) GetLastAppliedTime() float32 {
	if x != nil && x.LastAppliedTime != nil {
		return *x.LastAppliedTime
	}
	return 0
}

func (x *CModifierTableEntry) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return Default_CModifierTableEntry_Duration
}

func (x *CModifierTableEntry) GetCaster() uint32 {
	if x != nil && x.Caster != nil {
		return *x.Caster
	}
	return Default_CModifierTableEntry_Caster
}

func (x *CModifierTableEntry) GetAbility() uint32 {
	if x != nil && x.Ability != nil {
		return *x.Ability
	}
	return Default_CModifierTableEntry_Ability
}

func (x *CModifierTableEntry) GetAuraProviderSerialNumber() int32 {
	if x != nil && x.AuraProviderSerialNumber != nil {
		return *x.AuraProviderSerialNumber
	}
	return 0
}

func (x *CModifierTableEntry) GetAuraProviderEhandle() uint32 {
	if x != nil && x.AuraProviderEhandle != nil {
		return *x.AuraProviderEhandle
	}
	return Default_CModifierTableEntry_AuraProviderEhandle
}

func (x *CModifierTableEntry) GetAbilitySubclass() uint32 {
	if x != nil && x.AbilitySubclass != nil {
		return *x.AbilitySubclass
	}
	return Default_CModifierTableEntry_AbilitySubclass
}

func (x *CModifierTableEntry) GetInAuraRange() bool {
	if x != nil && x.InAuraRange != nil {
		return *x.InAuraRange
	}
	return false
}

func (x *CModifierTableEntry) GetBool1_() bool {
	if x != nil && x.Bool1_ != nil {
		return *x.Bool1_
	}
	return false
}

func (x *CModifierTableEntry) GetBool2_() bool {
	if x != nil && x.Bool2_ != nil {
		return *x.Bool2_
	}
	return false
}

func (x *CModifierTableEntry) GetBool3_() bool {
	if x != nil && x.Bool3_ != nil {
		return *x.Bool3_
	}
	return false
}

func (x *CModifierTableEntry) GetBool4_() bool {
	if x != nil && x.Bool4_ != nil {
		return *x.Bool4_
	}
	return false
}

func (x *CModifierTableEntry) GetInt1_() int32 {
	if x != nil && x.Int1_ != nil {
		return *x.Int1_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt2_() int32 {
	if x != nil && x.Int2_ != nil {
		return *x.Int2_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt3_() int32 {
	if x != nil && x.Int3_ != nil {
		return *x.Int3_
	}
	return 0
}

func (x *CModifierTableEntry) GetInt4_() int32 {
	if x != nil && x.Int4_ != nil {
		return *x.Int4_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat1_() float32 {
	if x != nil && x.Float1_ != nil {
		return *x.Float1_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat2_() float32 {
	if x != nil && x.Float2_ != nil {
		return *x.Float2_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat3_() float32 {
	if x != nil && x.Float3_ != nil {
		return *x.Float3_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat4_() float32 {
	if x != nil && x.Float4_ != nil {
		return *x.Float4_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat5_() float32 {
	if x != nil && x.Float5_ != nil {
		return *x.Float5_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat6_() float32 {
	if x != nil && x.Float6_ != nil {
		return *x.Float6_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat7_() float32 {
	if x != nil && x.Float7_ != nil {
		return *x.Float7_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat8_() float32 {
	if x != nil && x.Float8_ != nil {
		return *x.Float8_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat9_() float32 {
	if x != nil && x.Float9_ != nil {
		return *x.Float9_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat10_() float32 {
	if x != nil && x.Float10_ != nil {
		return *x.Float10_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat11_() float32 {
	if x != nil && x.Float11_ != nil {
		return *x.Float11_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat12_() float32 {
	if x != nil && x.Float12_ != nil {
		return *x.Float12_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat13_() float32 {
	if x != nil && x.Float13_ != nil {
		return *x.Float13_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat14_() float32 {
	if x != nil && x.Float14_ != nil {
		return *x.Float14_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat15_() float32 {
	if x != nil && x.Float15_ != nil {
		return *x.Float15_
	}
	return 0
}

func (x *CModifierTableEntry) GetFloat16_() float32 {
	if x != nil && x.Float16_ != nil {
		return *x.Float16_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint1_() uint64 {
	if x != nil && x.Uint1_ != nil {
		return *x.Uint1_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint2_() uint64 {
	if x != nil && x.Uint2_ != nil {
		return *x.Uint2_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint3_() uint64 {
	if x != nil && x.Uint3_ != nil {
		return *x.Uint3_
	}
	return 0
}

func (x *CModifierTableEntry) GetUint4_() uint64 {
	if x != nil && x.Uint4_ != nil {
		return *x.Uint4_
	}
	return 0
}

func (x *CModifierTableEntry) GetVec1_() *CMsgVector {
	if x != nil {
		return x.Vec1_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec2_() *CMsgVector {
	if x != nil {
		return x.Vec2_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec3_() *CMsgVector {
	if x != nil {
		return x.Vec3_
	}
	return nil
}

func (x *CModifierTableEntry) GetVec4_() *CMsgVector {
	if x != nil {
		return x.Vec4_
	}
	return nil
}

func (x *CModifierTableEntry) GetString1_() string {
	if x != nil && x.String1_ != nil {
		return *x.String1_
	}
	return ""
}

func (x *CModifierTableEntry) GetString2_() string {
	if x != nil && x.String2_ != nil {
		return *x.String2_
	}
	return ""
}

func (x *CModifierTableEntry) GetString3_() string {
	if x != nil && x.String3_ != nil {
		return *x.String3_
	}
	return ""
}

func (x *CModifierTableEntry) GetString4_() string {
	if x != nil && x.String4_ != nil {
		return *x.String4_
	}
	return ""
}

func (m *CModifierTableEntry) CloneVT() *CModifierTableEntry {
	if m == nil {
		return (*CModifierTableEntry)(nil)
	}
	r := new(CModifierTableEntry)
	r.Vec1_ = m.Vec1_.CloneVT()
	r.Vec2_ = m.Vec2_.CloneVT()
	r.Vec3_ = m.Vec3_.CloneVT()
	r.Vec4_ = m.Vec4_.CloneVT()
	if rhs := m.EntryType; rhs != nil {
		tmpVal := *rhs
		r.EntryType = &tmpVal
	}
	if rhs := m.Parent; rhs != nil {
		tmpVal := *rhs
		r.Parent = &tmpVal
	}
	if rhs := m.SerialNumber; rhs != nil {
		tmpVal := *rhs
		r.SerialNumber = &tmpVal
	}
	if rhs := m.ModifierSubclass; rhs != nil {
		tmpVal := *rhs
		r.ModifierSubclass = &tmpVal
	}
	if rhs := m.StackCount; rhs != nil {
		tmpVal := *rhs
		r.StackCount = &tmpVal
	}
	if rhs := m.MaxStackCount; rhs != nil {
		tmpVal := *rhs
		r.MaxStackCount = &tmpVal
	}
	if rhs := m.LastAppliedTime; rhs != nil {
		tmpVal := *rhs
		r.LastAppliedTime = &tmpVal
	}
	if rhs := m.Duration; rhs != nil {
		tmpVal := *rhs
		r.Duration = &tmpVal
	}
	if rhs := m.Caster; rhs != nil {
		tmpVal := *rhs
		r.Caster = &tmpVal
	}
	if rhs := m.Ability; rhs != nil {
		tmpVal := *rhs
		r.Ability = &tmpVal
	}
	if rhs := m.AuraProviderSerialNumber; rhs != nil {
		tmpVal := *rhs
		r.AuraProviderSerialNumber = &tmpVal
	}
	if rhs := m.AuraProviderEhandle; rhs != nil {
		tmpVal := *rhs
		r.AuraProviderEhandle = &tmpVal
	}
	if rhs := m.AbilitySubclass; rhs != nil {
		tmpVal := *rhs
		r.AbilitySubclass = &tmpVal
	}
	if rhs := m.InAuraRange; rhs != nil {
		tmpVal := *rhs
		r.InAuraRange = &tmpVal
	}
	if rhs := m.Bool1_; rhs != nil {
		tmpVal := *rhs
		r.Bool1_ = &tmpVal
	}
	if rhs := m.Bool2_; rhs != nil {
		tmpVal := *rhs
		r.Bool2_ = &tmpVal
	}
	if rhs := m.Bool3_; rhs != nil {
		tmpVal := *rhs
		r.Bool3_ = &tmpVal
	}
	if rhs := m.Bool4_; rhs != nil {
		tmpVal := *rhs
		r.Bool4_ = &tmpVal
	}
	if rhs := m.Int1_; rhs != nil {
		tmpVal := *rhs
		r.Int1_ = &tmpVal
	}
	if rhs := m.Int2_; rhs != nil {
		tmpVal := *rhs
		r.Int2_ = &tmpVal
	}
	if rhs := m.Int3_; rhs != nil {
		tmpVal := *rhs
		r.Int3_ = &tmpVal
	}
	if rhs := m.Int4_; rhs != nil {
		tmpVal := *rhs
		r.Int4_ = &tmpVal
	}
	if rhs := m.Float1_; rhs != nil {
		tmpVal := *rhs
		r.Float1_ = &tmpVal
	}
	if rhs := m.Float2_; rhs != nil {
		tmpVal := *rhs
		r.Float2_ = &tmpVal
	}
	if rhs := m.Float3_; rhs != nil {
		tmpVal := *rhs
		r.Float3_ = &tmpVal
	}
	if rhs := m.Float4_; rhs != nil {
		tmpVal := *rhs
		r.Float4_ = &tmpVal
	}
	if rhs := m.Float5_; rhs != nil {
		tmpVal := *rhs
		r.Float5_ = &tmpVal
	}
	if rhs := m.Float6_; rhs != nil {
		tmpVal := *rhs
		r.Float6_ = &tmpVal
	}
	if rhs := m.Float7_; rhs != nil {
		tmpVal := *rhs
		r.Float7_ = &tmpVal
	}
	if rhs := m.Float8_; rhs != nil {
		tmpVal := *rhs
		r.Float8_ = &tmpVal
	}
	if rhs := m.Float9_; rhs != nil {
		tmpVal := *rhs
		r.Float9_ = &tmpVal
	}
	if rhs := m.Float10_; rhs != nil {
		tmpVal := *rhs
		r.Float10_ = &tmpVal
	}
	if rhs := m.Float11_; rhs != nil {
		tmpVal := *rhs
		r.Float11_ = &tmpVal
	}
	if rhs := m.Float12_; rhs != nil {
		tmpVal := *rhs
		r.Float12_ = &tmpVal
	}
	if rhs := m.Float13_; rhs != nil {
		tmpVal := *rhs
		r.Float13_ = &tmpVal
	}
	if rhs := m.Float14_; rhs != nil {
		tmpVal := *rhs
		r.Float14_ = &tmpVal
	}
	if rhs := m.Float15_; rhs != nil {
		tmpVal := *rhs
		r.Float15_ = &tmpVal
	}
	if rhs := m.Float16_; rhs != nil {
		tmpVal := *rhs
		r.Float16_ = &tmpVal
	}
	if rhs := m.Uint1_; rhs != nil {
		tmpVal := *rhs
		r.Uint1_ = &tmpVal
	}
	if rhs := m.Uint2_; rhs != nil {
		tmpVal := *rhs
		r.Uint2_ = &tmpVal
	}
	if rhs := m.Uint3_; rhs != nil {
		tmpVal := *rhs
		r.Uint3_ = &tmpVal
	}
	if rhs := m.Uint4_; rhs != nil {
		tmpVal := *rhs
		r.Uint4_ = &tmpVal
	}
	if rhs := m.String1_; rhs != nil {
		tmpVal := *rhs
		r.String1_ = &tmpVal
	}
	if rhs := m.String2_; rhs != nil {
		tmpVal := *rhs
		r.String2_ = &tmpVal
	}
	if rhs := m.String3_; rhs != nil {
		tmpVal := *rhs
		r.String3_ = &tmpVal
	}
	if rhs := m.String4_; rhs != nil {
		tmpVal := *rhs
		r.String4_ = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CModifierTableEntry) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CModifierTableEntry) EqualVT(that *CModifierTableEntry) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.EntryType, that.EntryType; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Parent, that.Parent; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.SerialNumber, that.SerialNumber; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.ModifierSubclass, that.ModifierSubclass; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.StackCount, that.StackCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.MaxStackCount, that.MaxStackCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.LastAppliedTime, that.LastAppliedTime; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Duration, that.Duration; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Caster, that.Caster; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Ability, that.Ability; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.AuraProviderSerialNumber, that.AuraProviderSerialNumber; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.AuraProviderEhandle, that.AuraProviderEhandle; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.AbilitySubclass, that.AbilitySubclass; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.InAuraRange, that.InAuraRange; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Bool1_, that.Bool1_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Bool2_, that.Bool2_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Bool3_, that.Bool3_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Bool4_, that.Bool4_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Int1_, that.Int1_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Int2_, that.Int2_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Int3_, that.Int3_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Int4_, that.Int4_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float1_, that.Float1_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float2_, that.Float2_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float3_, that.Float3_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float4_, that.Float4_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Uint1_, that.Uint1_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Uint2_, that.Uint2_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Uint3_, that.Uint3_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Uint4_, that.Uint4_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if !this.Vec1_.EqualVT(that.Vec1_) {
		return false
	}
	if !this.Vec2_.EqualVT(that.Vec2_) {
		return false
	}
	if !this.Vec3_.EqualVT(that.Vec3_) {
		return false
	}
	if !this.Vec4_.EqualVT(that.Vec4_) {
		return false
	}
	if p, q := this.String1_, that.String1_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.String2_, that.String2_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.String3_, that.String3_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.String4_, that.String4_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float5_, that.Float5_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float6_, that.Float6_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float7_, that.Float7_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float8_, that.Float8_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float9_, that.Float9_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float10_, that.Float10_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float11_, that.Float11_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float12_, that.Float12_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float13_, that.Float13_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float14_, that.Float14_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float15_, that.Float15_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Float16_, that.Float16_; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CModifierTableEntry) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CModifierTableEntry)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *CModifierTableEntry) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CModifierTableEntry) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CModifierTableEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Float16_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float16_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xe5
	}
	if m.Float15_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float15_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xdd
	}
	if m.Float14_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float14_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xd5
	}
	if m.Float13_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float13_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xcd
	}
	if m.Float12_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float12_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xc5
	}
	if m.Float11_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float11_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xbd
	}
	if m.Float10_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float10_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xb5
	}
	if m.Float9_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float9_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xad
	}
	if m.Float8_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float8_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xa5
	}
	if m.Float7_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float7_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x9d
	}
	if m.Float6_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float6_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x95
	}
	if m.Float5_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float5_))))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x8d
	}
	if m.String4_ != nil {
		i -= len(*m.String4_)
		copy(dAtA[i:], *m.String4_)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.String4_)))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x82
	}
	if m.String3_ != nil {
		i -= len(*m.String3_)
		copy(dAtA[i:], *m.String3_)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.String3_)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xfa
	}
	if m.String2_ != nil {
		i -= len(*m.String2_)
		copy(dAtA[i:], *m.String2_)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.String2_)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xf2
	}
	if m.String1_ != nil {
		i -= len(*m.String1_)
		copy(dAtA[i:], *m.String1_)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.String1_)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xea
	}
	if m.Vec4_ != nil {
		size, err := m.Vec4_.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xda
	}
	if m.Vec3_ != nil {
		size, err := m.Vec3_.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd2
	}
	if m.Vec2_ != nil {
		size, err := m.Vec2_.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xca
	}
	if m.Vec1_ != nil {
		size, err := m.Vec1_.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc2
	}
	if m.Uint4_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Uint4_))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb0
	}
	if m.Uint3_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Uint3_))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa8
	}
	if m.Uint2_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Uint2_))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa0
	}
	if m.Uint1_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Uint1_))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.Float4_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float4_))))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x8d
	}
	if m.Float3_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float3_))))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x85
	}
	if m.Float2_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float2_))))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xfd
	}
	if m.Float1_ != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Float1_))))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf5
	}
	if m.Int4_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Int4_))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.Int3_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Int3_))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.Int2_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Int2_))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.Int1_ != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Int1_))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.Bool4_ != nil {
		i--
		if *m.Bool4_ {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.Bool3_ != nil {
		i--
		if *m.Bool3_ {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.Bool2_ != nil {
		i--
		if *m.Bool2_ {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.Bool1_ != nil {
		i--
		if *m.Bool1_ {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.InAuraRange != nil {
		i--
		if *m.InAuraRange {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.AbilitySubclass != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AbilitySubclass))
		i--
		dAtA[i] = 0x68
	}
	if m.AuraProviderEhandle != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AuraProviderEhandle))
		i--
		dAtA[i] = 0x60
	}
	if m.AuraProviderSerialNumber != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AuraProviderSerialNumber))
		i--
		dAtA[i] = 0x58
	}
	if m.Ability != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Ability))
		i--
		dAtA[i] = 0x50
	}
	if m.Caster != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Caster))
		i--
		dAtA[i] = 0x48
	}
	if m.Duration != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Duration))))
		i--
		dAtA[i] = 0x45
	}
	if m.LastAppliedTime != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.LastAppliedTime))))
		i--
		dAtA[i] = 0x3d
	}
	if m.MaxStackCount != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.MaxStackCount))
		i--
		dAtA[i] = 0x30
	}
	if m.StackCount != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.StackCount))
		i--
		dAtA[i] = 0x28
	}
	if m.ModifierSubclass != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.ModifierSubclass))
		i--
		dAtA[i] = 0x20
	}
	if m.SerialNumber != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.SerialNumber))
		i--
		dAtA[i] = 0x18
	}
	if m.Parent != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Parent))
		i--
		dAtA[i] = 0x10
	}
	if m.EntryType != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.EntryType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CModifierTableEntry) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EntryType != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.EntryType))
	}
	if m.Parent != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Parent))
	}
	if m.SerialNumber != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.SerialNumber))
	}
	if m.ModifierSubclass != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.ModifierSubclass))
	}
	if m.StackCount != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.StackCount))
	}
	if m.MaxStackCount != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.MaxStackCount))
	}
	if m.LastAppliedTime != nil {
		n += 5
	}
	if m.Duration != nil {
		n += 5
	}
	if m.Caster != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Caster))
	}
	if m.Ability != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Ability))
	}
	if m.AuraProviderSerialNumber != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.AuraProviderSerialNumber))
	}
	if m.AuraProviderEhandle != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.AuraProviderEhandle))
	}
	if m.AbilitySubclass != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.AbilitySubclass))
	}
	if m.InAuraRange != nil {
		n += 2
	}
	if m.Bool1_ != nil {
		n += 3
	}
	if m.Bool2_ != nil {
		n += 3
	}
	if m.Bool3_ != nil {
		n += 3
	}
	if m.Bool4_ != nil {
		n += 3
	}
	if m.Int1_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Int1_))
	}
	if m.Int2_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Int2_))
	}
	if m.Int3_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Int3_))
	}
	if m.Int4_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Int4_))
	}
	if m.Float1_ != nil {
		n += 6
	}
	if m.Float2_ != nil {
		n += 6
	}
	if m.Float3_ != nil {
		n += 6
	}
	if m.Float4_ != nil {
		n += 6
	}
	if m.Uint1_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Uint1_))
	}
	if m.Uint2_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Uint2_))
	}
	if m.Uint3_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Uint3_))
	}
	if m.Uint4_ != nil {
		n += 2 + protobuf_go_lite.SizeOfVarint(uint64(*m.Uint4_))
	}
	if m.Vec1_ != nil {
		l = m.Vec1_.SizeVT()
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Vec2_ != nil {
		l = m.Vec2_.SizeVT()
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Vec3_ != nil {
		l = m.Vec3_.SizeVT()
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Vec4_ != nil {
		l = m.Vec4_.SizeVT()
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.String1_ != nil {
		l = len(*m.String1_)
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.String2_ != nil {
		l = len(*m.String2_)
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.String3_ != nil {
		l = len(*m.String3_)
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.String4_ != nil {
		l = len(*m.String4_)
		n += 2 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Float5_ != nil {
		n += 6
	}
	if m.Float6_ != nil {
		n += 6
	}
	if m.Float7_ != nil {
		n += 6
	}
	if m.Float8_ != nil {
		n += 6
	}
	if m.Float9_ != nil {
		n += 6
	}
	if m.Float10_ != nil {
		n += 6
	}
	if m.Float11_ != nil {
		n += 6
	}
	if m.Float12_ != nil {
		n += 6
	}
	if m.Float13_ != nil {
		n += 6
	}
	if m.Float14_ != nil {
		n += 6
	}
	if m.Float15_ != nil {
		n += 6
	}
	if m.Float16_ != nil {
		n += 6
	}
	n += len(m.unknownFields)
	return n
}

func (x MODIFIER_ENTRY_TYPE) MarshalProtoText() string {
	return x.String()
}

func (x *CModifierTableEntry) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("CModifierTableEntry {")
	if x.EntryType != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("entry_type: ")
		sb.WriteString("\"")
		sb.WriteString(x.EntryType.String())
		sb.WriteString("\"")
	}
	if x.Parent != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("parent: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Parent), 10))
	}
	if x.SerialNumber != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("serial_number: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.SerialNumber), 10))
	}
	if x.ModifierSubclass != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("modifier_subclass: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.ModifierSubclass), 10))
	}
	if x.StackCount != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("stack_count: ")
		sb.WriteString(strconv.FormatInt(int64(*x.StackCount), 10))
	}
	if x.MaxStackCount != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("max_stack_count: ")
		sb.WriteString(strconv.FormatInt(int64(*x.MaxStackCount), 10))
	}
	if x.LastAppliedTime != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("last_applied_time: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.LastAppliedTime), 'g', -1, 32))
	}
	if x.Duration != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("duration: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Duration), 'g', -1, 32))
	}
	if x.Caster != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("caster: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Caster), 10))
	}
	if x.Ability != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("ability: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Ability), 10))
	}
	if x.AuraProviderSerialNumber != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("aura_provider_serial_number: ")
		sb.WriteString(strconv.FormatInt(int64(*x.AuraProviderSerialNumber), 10))
	}
	if x.AuraProviderEhandle != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("aura_provider_ehandle: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.AuraProviderEhandle), 10))
	}
	if x.AbilitySubclass != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("ability_subclass: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.AbilitySubclass), 10))
	}
	if x.InAuraRange != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("in_aura_range: ")
		sb.WriteString(strconv.FormatBool(*x.InAuraRange))
	}
	if x.Bool1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("bool1_: ")
		sb.WriteString(strconv.FormatBool(*x.Bool1_))
	}
	if x.Bool2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("bool2_: ")
		sb.WriteString(strconv.FormatBool(*x.Bool2_))
	}
	if x.Bool3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("bool3_: ")
		sb.WriteString(strconv.FormatBool(*x.Bool3_))
	}
	if x.Bool4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("bool4_: ")
		sb.WriteString(strconv.FormatBool(*x.Bool4_))
	}
	if x.Int1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("int1_: ")
		sb.WriteString(strconv.FormatInt(int64(*x.Int1_), 10))
	}
	if x.Int2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("int2_: ")
		sb.WriteString(strconv.FormatInt(int64(*x.Int2_), 10))
	}
	if x.Int3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("int3_: ")
		sb.WriteString(strconv.FormatInt(int64(*x.Int3_), 10))
	}
	if x.Int4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("int4_: ")
		sb.WriteString(strconv.FormatInt(int64(*x.Int4_), 10))
	}
	if x.Float1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float1_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float1_), 'g', -1, 32))
	}
	if x.Float2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float2_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float2_), 'g', -1, 32))
	}
	if x.Float3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float3_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float3_), 'g', -1, 32))
	}
	if x.Float4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float4_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float4_), 'g', -1, 32))
	}
	if x.Uint1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("uint1_: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Uint1_), 10))
	}
	if x.Uint2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("uint2_: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Uint2_), 10))
	}
	if x.Uint3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("uint3_: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Uint3_), 10))
	}
	if x.Uint4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("uint4_: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Uint4_), 10))
	}
	if x.Vec1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("vec1_: ")
		sb.WriteString(x.Vec1_.MarshalProtoText())
	}
	if x.Vec2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("vec2_: ")
		sb.WriteString(x.Vec2_.MarshalProtoText())
	}
	if x.Vec3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("vec3_: ")
		sb.WriteString(x.Vec3_.MarshalProtoText())
	}
	if x.Vec4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("vec4_: ")
		sb.WriteString(x.Vec4_.MarshalProtoText())
	}
	if x.String1_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("string1_: ")
		sb.WriteString(strconv.Quote(*x.String1_))
	}
	if x.String2_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("string2_: ")
		sb.WriteString(strconv.Quote(*x.String2_))
	}
	if x.String3_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("string3_: ")
		sb.WriteString(strconv.Quote(*x.String3_))
	}
	if x.String4_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("string4_: ")
		sb.WriteString(strconv.Quote(*x.String4_))
	}
	if x.Float5_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float5_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float5_), 'g', -1, 32))
	}
	if x.Float6_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float6_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float6_), 'g', -1, 32))
	}
	if x.Float7_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float7_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float7_), 'g', -1, 32))
	}
	if x.Float8_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float8_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float8_), 'g', -1, 32))
	}
	if x.Float9_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float9_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float9_), 'g', -1, 32))
	}
	if x.Float10_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float10_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float10_), 'g', -1, 32))
	}
	if x.Float11_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float11_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float11_), 'g', -1, 32))
	}
	if x.Float12_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float12_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float12_), 'g', -1, 32))
	}
	if x.Float13_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float13_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float13_), 'g', -1, 32))
	}
	if x.Float14_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float14_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float14_), 'g', -1, 32))
	}
	if x.Float15_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float15_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float15_), 'g', -1, 32))
	}
	if x.Float16_ != nil {
		if sb.Len() > 21 {
			sb.WriteString(" ")
		}
		sb.WriteString("float16_: ")
		sb.WriteString(strconv.FormatFloat(float64(*x.Float16_), 'g', -1, 32))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *CModifierTableEntry) String() string {
	return x.MarshalProtoText()
}

func (m *CModifierTableEntry) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CModifierTableEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CModifierTableEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryType", wireType)
			}
			var v MODIFIER_ENTRY_TYPE
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = MODIFIER_ENTRY_TYPE(_v)
			if err != nil {
				return err
			}
			m.EntryType = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Parent = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerialNumber", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SerialNumber = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModifierSubclass", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ModifierSubclass = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StackCount", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.StackCount = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStackCount", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.MaxStackCount = &v
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAppliedTime", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.LastAppliedTime = &v2
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Duration = &v2
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caster", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Caster = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ability", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Ability = &v
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuraProviderSerialNumber", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AuraProviderSerialNumber = &v
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuraProviderEhandle", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AuraProviderEhandle = &v
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AbilitySubclass", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AbilitySubclass = &v
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InAuraRange", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.InAuraRange = &b
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bool1_", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.Bool1_ = &b
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bool2_", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.Bool2_ = &b
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bool3_", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.Bool3_ = &b
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bool4_", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.Bool4_ = &b
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int1_", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Int1_ = &v
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int2_", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Int2_ = &v
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int3_", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Int3_ = &v
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int4_", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Int4_ = &v
		case 30:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float1_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float1_ = &v2
		case 31:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float2_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float2_ = &v2
		case 32:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float3_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float3_ = &v2
		case 33:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float4_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float4_ = &v2
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint1_", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Uint1_ = &v
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint2_", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Uint2_ = &v
		case 37:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint3_", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Uint3_ = &v
		case 38:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint4_", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Uint4_ = &v
		case 40:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vec1_", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vec1_ == nil {
				m.Vec1_ = &CMsgVector{}
			}
			if err := m.Vec1_.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vec2_", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vec2_ == nil {
				m.Vec2_ = &CMsgVector{}
			}
			if err := m.Vec2_.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 42:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vec3_", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vec3_ == nil {
				m.Vec3_ = &CMsgVector{}
			}
			if err := m.Vec3_.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 43:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vec4_", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vec4_ == nil {
				m.Vec4_ = &CMsgVector{}
			}
			if err := m.Vec4_.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 45:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String1_", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.String1_ = &s
			iNdEx = postIndex
		case 46:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String2_", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.String2_ = &s
			iNdEx = postIndex
		case 47:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String3_", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.String3_ = &s
			iNdEx = postIndex
		case 48:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String4_", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.String4_ = &s
			iNdEx = postIndex
		case 49:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float5_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float5_ = &v2
		case 50:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float6_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float6_ = &v2
		case 51:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float7_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float7_ = &v2
		case 52:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float8_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float8_ = &v2
		case 53:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float9_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float9_ = &v2
		case 54:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float10_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float10_ = &v2
		case 55:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float11_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float11_ = &v2
		case 56:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float12_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float12_ = &v2
		case 57:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float13_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float13_ = &v2
		case 58:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float14_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float14_ = &v2
		case 59:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float15_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float15_ = &v2
		case 60:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float16_", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Float16_ = &v2
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
