// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.14.0
// source: github.com/paralin/s2replay/protocol/networksystem_protomessages.proto

package protocol

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
)

type NetMessageSplitscreenUserChanged struct {
	unknownFields []byte
	Slot          *uint32 `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
}

func (x *NetMessageSplitscreenUserChanged) Reset() {
	*x = NetMessageSplitscreenUserChanged{}
}

func (*NetMessageSplitscreenUserChanged) ProtoMessage() {}

func (x *NetMessageSplitscreenUserChanged) GetSlot() uint32 {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return 0
}

type NetMessageConnectionClosed struct {
	unknownFields []byte
	Reason        *uint32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
	Message       *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *NetMessageConnectionClosed) Reset() {
	*x = NetMessageConnectionClosed{}
}

func (*NetMessageConnectionClosed) ProtoMessage() {}

func (x *NetMessageConnectionClosed) GetReason() uint32 {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return 0
}

func (x *NetMessageConnectionClosed) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type NetMessageConnectionCrashed struct {
	unknownFields []byte
	Reason        *uint32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
	Message       *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *NetMessageConnectionCrashed) Reset() {
	*x = NetMessageConnectionCrashed{}
}

func (*NetMessageConnectionCrashed) ProtoMessage() {}

func (x *NetMessageConnectionCrashed) GetReason() uint32 {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return 0
}

func (x *NetMessageConnectionCrashed) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type NetMessagePacketStart struct {
	unknownFields []byte
}

func (x *NetMessagePacketStart) Reset() {
	*x = NetMessagePacketStart{}
}

func (*NetMessagePacketStart) ProtoMessage() {}

type NetMessagePacketEnd struct {
	unknownFields []byte
}

func (x *NetMessagePacketEnd) Reset() {
	*x = NetMessagePacketEnd{}
}

func (*NetMessagePacketEnd) ProtoMessage() {}

func (m *NetMessageSplitscreenUserChanged) CloneVT() *NetMessageSplitscreenUserChanged {
	if m == nil {
		return (*NetMessageSplitscreenUserChanged)(nil)
	}
	r := new(NetMessageSplitscreenUserChanged)
	if rhs := m.Slot; rhs != nil {
		tmpVal := *rhs
		r.Slot = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *NetMessageSplitscreenUserChanged) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *NetMessageConnectionClosed) CloneVT() *NetMessageConnectionClosed {
	if m == nil {
		return (*NetMessageConnectionClosed)(nil)
	}
	r := new(NetMessageConnectionClosed)
	if rhs := m.Reason; rhs != nil {
		tmpVal := *rhs
		r.Reason = &tmpVal
	}
	if rhs := m.Message; rhs != nil {
		tmpVal := *rhs
		r.Message = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *NetMessageConnectionClosed) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *NetMessageConnectionCrashed) CloneVT() *NetMessageConnectionCrashed {
	if m == nil {
		return (*NetMessageConnectionCrashed)(nil)
	}
	r := new(NetMessageConnectionCrashed)
	if rhs := m.Reason; rhs != nil {
		tmpVal := *rhs
		r.Reason = &tmpVal
	}
	if rhs := m.Message; rhs != nil {
		tmpVal := *rhs
		r.Message = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *NetMessageConnectionCrashed) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *NetMessagePacketStart) CloneVT() *NetMessagePacketStart {
	if m == nil {
		return (*NetMessagePacketStart)(nil)
	}
	r := new(NetMessagePacketStart)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *NetMessagePacketStart) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *NetMessagePacketEnd) CloneVT() *NetMessagePacketEnd {
	if m == nil {
		return (*NetMessagePacketEnd)(nil)
	}
	r := new(NetMessagePacketEnd)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *NetMessagePacketEnd) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *NetMessageSplitscreenUserChanged) EqualVT(that *NetMessageSplitscreenUserChanged) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Slot, that.Slot; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *NetMessageSplitscreenUserChanged) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*NetMessageSplitscreenUserChanged)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *NetMessageConnectionClosed) EqualVT(that *NetMessageConnectionClosed) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Reason, that.Reason; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Message, that.Message; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *NetMessageConnectionClosed) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*NetMessageConnectionClosed)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *NetMessageConnectionCrashed) EqualVT(that *NetMessageConnectionCrashed) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Reason, that.Reason; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Message, that.Message; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *NetMessageConnectionCrashed) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*NetMessageConnectionCrashed)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *NetMessagePacketStart) EqualVT(that *NetMessagePacketStart) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *NetMessagePacketStart) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*NetMessagePacketStart)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *NetMessagePacketEnd) EqualVT(that *NetMessagePacketEnd) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *NetMessagePacketEnd) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*NetMessagePacketEnd)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *NetMessageSplitscreenUserChanged) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetMessageSplitscreenUserChanged) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *NetMessageSplitscreenUserChanged) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Slot != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Slot))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NetMessageConnectionClosed) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetMessageConnectionClosed) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *NetMessageConnectionClosed) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Message != nil {
		i -= len(*m.Message)
		copy(dAtA[i:], *m.Message)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Reason != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Reason))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NetMessageConnectionCrashed) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetMessageConnectionCrashed) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *NetMessageConnectionCrashed) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Message != nil {
		i -= len(*m.Message)
		copy(dAtA[i:], *m.Message)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Reason != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Reason))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NetMessagePacketStart) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetMessagePacketStart) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *NetMessagePacketStart) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	return len(dAtA) - i, nil
}

func (m *NetMessagePacketEnd) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetMessagePacketEnd) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *NetMessagePacketEnd) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	return len(dAtA) - i, nil
}

func (m *NetMessageSplitscreenUserChanged) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Slot != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Slot))
	}
	n += len(m.unknownFields)
	return n
}

func (m *NetMessageConnectionClosed) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reason != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Reason))
	}
	if m.Message != nil {
		l = len(*m.Message)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *NetMessageConnectionCrashed) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reason != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Reason))
	}
	if m.Message != nil {
		l = len(*m.Message)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *NetMessagePacketStart) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += len(m.unknownFields)
	return n
}

func (m *NetMessagePacketEnd) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += len(m.unknownFields)
	return n
}

func (x *NetMessageSplitscreenUserChanged) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("NetMessageSplitscreenUserChanged {")
	if x.Slot != nil {
		if sb.Len() > 34 {
			sb.WriteString(" ")
		}
		sb.WriteString("slot: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Slot), 10))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *NetMessageSplitscreenUserChanged) String() string {
	return x.MarshalProtoText()
}

func (x *NetMessageConnectionClosed) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("NetMessageConnectionClosed {")
	if x.Reason != nil {
		if sb.Len() > 28 {
			sb.WriteString(" ")
		}
		sb.WriteString("reason: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Reason), 10))
	}
	if x.Message != nil {
		if sb.Len() > 28 {
			sb.WriteString(" ")
		}
		sb.WriteString("message: ")
		sb.WriteString(strconv.Quote(*x.Message))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *NetMessageConnectionClosed) String() string {
	return x.MarshalProtoText()
}

func (x *NetMessageConnectionCrashed) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("NetMessageConnectionCrashed {")
	if x.Reason != nil {
		if sb.Len() > 29 {
			sb.WriteString(" ")
		}
		sb.WriteString("reason: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Reason), 10))
	}
	if x.Message != nil {
		if sb.Len() > 29 {
			sb.WriteString(" ")
		}
		sb.WriteString("message: ")
		sb.WriteString(strconv.Quote(*x.Message))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *NetMessageConnectionCrashed) String() string {
	return x.MarshalProtoText()
}

func (x *NetMessagePacketStart) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("NetMessagePacketStart {")
	sb.WriteString("}")
	return sb.String()
}

func (x *NetMessagePacketStart) String() string {
	return x.MarshalProtoText()
}

func (x *NetMessagePacketEnd) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("NetMessagePacketEnd {")
	sb.WriteString("}")
	return sb.String()
}

func (x *NetMessagePacketEnd) String() string {
	return x.MarshalProtoText()
}

func (m *NetMessageSplitscreenUserChanged) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetMessageSplitscreenUserChanged: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetMessageSplitscreenUserChanged: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Slot = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NetMessageConnectionClosed) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetMessageConnectionClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetMessageConnectionClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Reason = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Message = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NetMessageConnectionCrashed) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetMessageConnectionCrashed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetMessageConnectionCrashed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Reason = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Message = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NetMessagePacketStart) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetMessagePacketStart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetMessagePacketStart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *NetMessagePacketEnd) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetMessagePacketEnd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetMessagePacketEnd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
