// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package analysis

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis(in *jlexer.Lexer, out *RunbackFacts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "schema_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SchemaVersion = int(in.Int())
			}
		case "source":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis1(in, &out.Source)
		case "correspondence":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis2(in, &out.Correspondence)
		case "tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tick = uint32(in.Uint32())
			}
		case "tick_provenance":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis3(in, &out.TickProvenance)
		case "heroes":
			if in.IsNull() {
				in.Skip()
				out.Heroes = nil
			} else {
				in.Delim('[')
				if out.Heroes == nil {
					if !in.IsDelim(']') {
						out.Heroes = make([]RunbackHero, 0, 0)
					} else {
						out.Heroes = []RunbackHero{}
					}
				} else {
					out.Heroes = (out.Heroes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 RunbackHero
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis4(in, &v1)
					out.Heroes = append(out.Heroes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "world_entities":
			if in.IsNull() {
				in.Skip()
				out.WorldEntities = nil
			} else {
				in.Delim('[')
				if out.WorldEntities == nil {
					if !in.IsDelim(']') {
						out.WorldEntities = make([]RunbackWorldEntity, 0, 0)
					} else {
						out.WorldEntities = []RunbackWorldEntity{}
					}
				} else {
					out.WorldEntities = (out.WorldEntities)[:0]
				}
				for !in.IsDelim(']') {
					var v2 RunbackWorldEntity
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis5(in, &v2)
					out.WorldEntities = append(out.WorldEntities, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "objectives":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis6(in, &out.Objectives)
		case "quality":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis7(in, &out.Quality)
		case "eligibility":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Eligibility = ReplaySegmentEligibility(in.String())
			}
		case "eligibility_reasons":
			if in.IsNull() {
				in.Skip()
				out.EligibilityReasons = nil
			} else {
				in.Delim('[')
				if out.EligibilityReasons == nil {
					if !in.IsDelim(']') {
						out.EligibilityReasons = make([]string, 0, 4)
					} else {
						out.EligibilityReasons = []string{}
					}
				} else {
					out.EligibilityReasons = (out.EligibilityReasons)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.EligibilityReasons = append(out.EligibilityReasons, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis(out *jwriter.Writer, in RunbackFacts) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"schema_version\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SchemaVersion))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis1(out, in.Source)
	}
	{
		const prefix string = ",\"correspondence\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis2(out, in.Correspondence)
	}
	{
		const prefix string = ",\"tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Tick))
	}
	{
		const prefix string = ",\"tick_provenance\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis3(out, in.TickProvenance)
	}
	{
		const prefix string = ",\"heroes\":"
		out.RawString(prefix)
		if in.Heroes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Heroes {
				if v4 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis4(out, v5)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"world_entities\":"
		out.RawString(prefix)
		if in.WorldEntities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.WorldEntities {
				if v6 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis5(out, v7)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"objectives\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis6(out, in.Objectives)
	}
	{
		const prefix string = ",\"quality\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis7(out, in.Quality)
	}
	{
		const prefix string = ",\"eligibility\":"
		out.RawString(prefix)
		out.String(string(in.Eligibility))
	}
	if len(in.EligibilityReasons) != 0 {
		const prefix string = ",\"eligibility_reasons\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.EligibilityReasons {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RunbackFacts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RunbackFacts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RunbackFacts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RunbackFacts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis(l, v)
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis7(in *jlexer.Lexer, out *RunbackFactsQuality) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "heroes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Heroes = int(in.Int())
			}
		case "world_entities":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorldEntities = int(in.Int())
			}
		case "snapshot_entities":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SnapshotEntities = int(in.Int())
			}
		case "unattributed_pawns":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnattributedPawns = int(in.Int())
			}
		case "duplicate_slots":
			if in.IsNull() {
				in.Skip()
				out.DuplicateSlots = nil
			} else {
				in.Delim('[')
				if out.DuplicateSlots == nil {
					if !in.IsDelim(']') {
						out.DuplicateSlots = make([]int32, 0, 16)
					} else {
						out.DuplicateSlots = []int32{}
					}
				} else {
					out.DuplicateSlots = (out.DuplicateSlots)[:0]
				}
				for !in.IsDelim(']') {
					var v10 int32
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = int32(in.Int32())
					}
					out.DuplicateSlots = append(out.DuplicateSlots, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "missing_fields":
			if in.IsNull() {
				in.Skip()
				out.MissingFields = nil
			} else {
				in.Delim('[')
				if out.MissingFields == nil {
					if !in.IsDelim(']') {
						out.MissingFields = make([]string, 0, 4)
					} else {
						out.MissingFields = []string{}
					}
				} else {
					out.MissingFields = (out.MissingFields)[:0]
				}
				for !in.IsDelim(']') {
					var v11 string
					if in.IsNull() {
						in.Skip()
					} else {
						v11 = string(in.String())
					}
					out.MissingFields = append(out.MissingFields, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis7(out *jwriter.Writer, in RunbackFactsQuality) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"heroes\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Heroes))
	}
	{
		const prefix string = ",\"world_entities\":"
		out.RawString(prefix)
		out.Int(int(in.WorldEntities))
	}
	{
		const prefix string = ",\"snapshot_entities\":"
		out.RawString(prefix)
		out.Int(int(in.SnapshotEntities))
	}
	{
		const prefix string = ",\"unattributed_pawns\":"
		out.RawString(prefix)
		out.Int(int(in.UnattributedPawns))
	}
	if len(in.DuplicateSlots) != 0 {
		const prefix string = ",\"duplicate_slots\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v12, v13 := range in.DuplicateSlots {
				if v12 > 0 {
					out.RawByte(',')
				}
				out.Int32(int32(v13))
			}
			out.RawByte(']')
		}
	}
	if len(in.MissingFields) != 0 {
		const prefix string = ",\"missing_fields\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v14, v15 := range in.MissingFields {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.String(string(v15))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis6(in *jlexer.Lexer, out *RunbackObjectives) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mid_boss":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis8(in, &out.MidBoss)
		case "rejuvenator":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis9(in, &out.Rejuvenator)
		case "towers":
			if in.IsNull() {
				in.Skip()
				out.Towers = nil
			} else {
				in.Delim('[')
				if out.Towers == nil {
					if !in.IsDelim(']') {
						out.Towers = make([]RunbackObjectiveEntity, 0, 0)
					} else {
						out.Towers = []RunbackObjectiveEntity{}
					}
				} else {
					out.Towers = (out.Towers)[:0]
				}
				for !in.IsDelim(']') {
					var v16 RunbackObjectiveEntity
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis8(in, &v16)
					out.Towers = append(out.Towers, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "walkers":
			if in.IsNull() {
				in.Skip()
				out.Walkers = nil
			} else {
				in.Delim('[')
				if out.Walkers == nil {
					if !in.IsDelim(']') {
						out.Walkers = make([]RunbackObjectiveEntity, 0, 0)
					} else {
						out.Walkers = []RunbackObjectiveEntity{}
					}
				} else {
					out.Walkers = (out.Walkers)[:0]
				}
				for !in.IsDelim(']') {
					var v17 RunbackObjectiveEntity
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis8(in, &v17)
					out.Walkers = append(out.Walkers, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "transients":
			if in.IsNull() {
				in.Skip()
				out.Transients = nil
			} else {
				in.Delim('[')
				if out.Transients == nil {
					if !in.IsDelim(']') {
						out.Transients = make([]RunbackTransient, 0, 0)
					} else {
						out.Transients = []RunbackTransient{}
					}
				} else {
					out.Transients = (out.Transients)[:0]
				}
				for !in.IsDelim(']') {
					var v18 RunbackTransient
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis10(in, &v18)
					out.Transients = append(out.Transients, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis6(out *jwriter.Writer, in RunbackObjectives) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mid_boss\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis8(out, in.MidBoss)
	}
	{
		const prefix string = ",\"rejuvenator\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis9(out, in.Rejuvenator)
	}
	{
		const prefix string = ",\"towers\":"
		out.RawString(prefix)
		if in.Towers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v19, v20 := range in.Towers {
				if v19 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis8(out, v20)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"walkers\":"
		out.RawString(prefix)
		if in.Walkers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v21, v22 := range in.Walkers {
				if v21 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis8(out, v22)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"transients\":"
		out.RawString(prefix)
		if in.Transients == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Transients {
				if v23 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis10(out, v24)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis10(in *jlexer.Lexer, out *RunbackTransient) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "owner_entity":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.OwnerEntity)
		case "team":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Team)
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v25 := 0
				for !in.IsDelim(']') {
					if v25 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Position)[v25])
						v25++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "missing_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MissingReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis10(out *jwriter.Writer, in RunbackTransient) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"owner_entity\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.OwnerEntity)
	}
	{
		const prefix string = ",\"team\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Team)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v26 := range in.Position {
			if v26 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Position)[v26])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"missing_reason\":"
		out.RawString(prefix)
		out.String(string(in.MissingReason))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in *jlexer.Lexer, out *RunbackFloat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float32(in.Float32())
			}
		case "present":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Present = bool(in.Bool())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		case "freshness_ticks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FreshnessTicks = uint32(in.Uint32())
			}
		case "missing_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MissingReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out *jwriter.Writer, in RunbackFloat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.Float32(float32(in.Value))
	}
	{
		const prefix string = ",\"present\":"
		out.RawString(prefix)
		out.Bool(bool(in.Present))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	{
		const prefix string = ",\"freshness_ticks\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FreshnessTicks))
	}
	if in.MissingReason != "" {
		const prefix string = ",\"missing_reason\":"
		out.RawString(prefix)
		out.String(string(in.MissingReason))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in *jlexer.Lexer, out *RunbackInt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int32(in.Int32())
			}
		case "present":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Present = bool(in.Bool())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		case "freshness_ticks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FreshnessTicks = uint32(in.Uint32())
			}
		case "missing_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MissingReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out *jwriter.Writer, in RunbackInt) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.Value))
	}
	{
		const prefix string = ",\"present\":"
		out.RawString(prefix)
		out.Bool(bool(in.Present))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	{
		const prefix string = ",\"freshness_ticks\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FreshnessTicks))
	}
	if in.MissingReason != "" {
		const prefix string = ",\"missing_reason\":"
		out.RawString(prefix)
		out.String(string(in.MissingReason))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis9(in *jlexer.Lexer, out *RunbackRejuvenator) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "last":
			if in.IsNull() {
				in.Skip()
				out.Last = nil
			} else {
				if out.Last == nil {
					out.Last = new(RunbackRejuvenatorEvent)
				}
				easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis13(in, out.Last)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis9(out *jwriter.Writer, in RunbackRejuvenator) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.Last != nil {
		const prefix string = ",\"last\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis13(out, *in.Last)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis13(in *jlexer.Lexer, out *RunbackRejuvenatorEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tick = uint32(in.Uint32())
			}
		case "killing_team":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KillingTeam = int32(in.Int32())
			}
		case "event_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventType = int32(in.Int32())
			}
		case "user_team":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserTeam = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis13(out *jwriter.Writer, in RunbackRejuvenatorEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tick\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.Tick))
	}
	{
		const prefix string = ",\"killing_team\":"
		out.RawString(prefix)
		out.Int32(int32(in.KillingTeam))
	}
	{
		const prefix string = ",\"event_type\":"
		out.RawString(prefix)
		out.Int32(int32(in.EventType))
	}
	{
		const prefix string = ",\"user_team\":"
		out.RawString(prefix)
		out.Int32(int32(in.UserTeam))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis8(in *jlexer.Lexer, out *RunbackObjectiveEntity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "team":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Team)
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v27 := 0
				for !in.IsDelim(']') {
					if v27 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Position)[v27])
						v27++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.Health)
		case "max_health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.MaxHealth)
		case "alive":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis14(in, &out.Alive)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis8(out *jwriter.Writer, in RunbackObjectiveEntity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.ClassID))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"team\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Team)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v28 := range in.Position {
			if v28 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Position)[v28])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.Health)
	}
	{
		const prefix string = ",\"max_health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.MaxHealth)
	}
	{
		const prefix string = ",\"alive\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis14(out, in.Alive)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis14(in *jlexer.Lexer, out *RunbackAlive) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alive = bool(in.Bool())
			}
		case "basis":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Basis = RunbackAliveBasis(in.String())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		case "freshness_ticks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FreshnessTicks = uint32(in.Uint32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis14(out *jwriter.Writer, in RunbackAlive) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alive\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Alive))
	}
	{
		const prefix string = ",\"basis\":"
		out.RawString(prefix)
		out.String(string(in.Basis))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	{
		const prefix string = ",\"freshness_ticks\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FreshnessTicks))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis5(in *jlexer.Lexer, out *RunbackWorldEntity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "team":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Team)
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v29 := 0
				for !in.IsDelim(']') {
					if v29 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Position)[v29])
						v29++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.Health)
		case "max_health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.MaxHealth)
		case "shield":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.Shield)
		case "alive":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis14(in, &out.Alive)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis5(out *jwriter.Writer, in RunbackWorldEntity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.ClassID))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"team\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Team)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v30 := range in.Position {
			if v30 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Position)[v30])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.Health)
	}
	{
		const prefix string = ",\"max_health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.MaxHealth)
	}
	{
		const prefix string = ",\"shield\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.Shield)
	}
	{
		const prefix string = ",\"alive\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis14(out, in.Alive)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis4(in *jlexer.Lexer, out *RunbackHero) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "camera_angles":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v31 := 0
				for !in.IsDelim(']') {
					if v31 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.CameraAngles)[v31])
						v31++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stamina_latch_time":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.StaminaLatchTime)
		case "stamina_latch_value":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.StaminaLatchValue)
		case "player_slot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PlayerSlot = int32(in.Int32())
			}
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "hero_id":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.HeroID)
		case "team":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Team)
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v32 := 0
				for !in.IsDelim(']') {
					if v32 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Position)[v32])
						v32++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "facing":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v33 := 0
				for !in.IsDelim(']') {
					if v33 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Facing)[v33])
						v33++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "velocity":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v34 := 0
				for !in.IsDelim(']') {
					if v34 < 3 {
						easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &(out.Velocity)[v34])
						v34++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.Health)
		case "max_health":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.MaxHealth)
		case "shield":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.Shield)
		case "max_shield":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.MaxShield)
		case "level":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.Level)
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]RunbackItem, 0, 0)
					} else {
						out.Items = []RunbackItem{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v35 RunbackItem
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis16(in, &v35)
					out.Items = append(out.Items, v35)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "abilities":
			if in.IsNull() {
				in.Skip()
				out.Abilities = nil
			} else {
				in.Delim('[')
				if out.Abilities == nil {
					if !in.IsDelim(']') {
						out.Abilities = make([]RunbackAbility, 0, 0)
					} else {
						out.Abilities = []RunbackAbility{}
					}
				} else {
					out.Abilities = (out.Abilities)[:0]
				}
				for !in.IsDelim(']') {
					var v36 RunbackAbility
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis17(in, &v36)
					out.Abilities = append(out.Abilities, v36)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "modifiers":
			if in.IsNull() {
				in.Skip()
				out.Modifiers = nil
			} else {
				in.Delim('[')
				if out.Modifiers == nil {
					if !in.IsDelim(']') {
						out.Modifiers = make([]RunbackModifier, 0, 0)
					} else {
						out.Modifiers = []RunbackModifier{}
					}
				} else {
					out.Modifiers = (out.Modifiers)[:0]
				}
				for !in.IsDelim(']') {
					var v37 RunbackModifier
					easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis18(in, &v37)
					out.Modifiers = append(out.Modifiers, v37)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "net_worth":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.NetWorth)
		case "scores":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis19(in, &out.Scores)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis4(out *jwriter.Writer, in RunbackHero) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"camera_angles\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v38 := range in.CameraAngles {
			if v38 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.CameraAngles)[v38])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"stamina_latch_time\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.StaminaLatchTime)
	}
	{
		const prefix string = ",\"stamina_latch_value\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.StaminaLatchValue)
	}
	{
		const prefix string = ",\"player_slot\":"
		out.RawString(prefix)
		out.Int32(int32(in.PlayerSlot))
	}
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.ClassID))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"hero_id\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.HeroID)
	}
	{
		const prefix string = ",\"team\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Team)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v39 := range in.Position {
			if v39 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Position)[v39])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"facing\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v40 := range in.Facing {
			if v40 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Facing)[v40])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"velocity\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v41 := range in.Velocity {
			if v41 > 0 {
				out.RawByte(',')
			}
			easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, (in.Velocity)[v41])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.Health)
	}
	{
		const prefix string = ",\"max_health\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.MaxHealth)
	}
	{
		const prefix string = ",\"shield\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.Shield)
	}
	{
		const prefix string = ",\"max_shield\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.MaxShield)
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.Level)
	}
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix)
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v42, v43 := range in.Items {
				if v42 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis16(out, v43)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"abilities\":"
		out.RawString(prefix)
		if in.Abilities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v44, v45 := range in.Abilities {
				if v44 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis17(out, v45)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"modifiers\":"
		out.RawString(prefix)
		if in.Modifiers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v46, v47 := range in.Modifiers {
				if v46 > 0 {
					out.RawByte(',')
				}
				easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis18(out, v47)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"net_worth\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.NetWorth)
	}
	{
		const prefix string = ",\"scores\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis19(out, in.Scores)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis19(in *jlexer.Lexer, out *RunbackScores) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "deaths":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Deaths)
		case "last_hits":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.LastHits)
		case "denies":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Denies)
		case "kill_streak":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.KillStreak)
		case "hero_damage":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.HeroDamage)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis19(out *jwriter.Writer, in RunbackScores) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"deaths\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Deaths)
	}
	{
		const prefix string = ",\"last_hits\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.LastHits)
	}
	{
		const prefix string = ",\"denies\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Denies)
	}
	{
		const prefix string = ",\"kill_streak\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.KillStreak)
	}
	{
		const prefix string = ",\"hero_damage\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.HeroDamage)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis18(in *jlexer.Lexer, out *RunbackModifier) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "payload_proto":
			if in.IsNull() {
				in.Skip()
				out.PayloadProto = nil
			} else {
				out.PayloadProto = in.Bytes()
			}
		case "table_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TableIndex = int32(in.Int32())
			}
		case "serial_number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SerialNumber = uint32(in.Uint32())
			}
		case "has_serial_number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasSerialNumber = bool(in.Bool())
			}
		case "parent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Parent = uint32(in.Uint32())
			}
		case "caster":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Caster = uint32(in.Uint32())
			}
		case "ability_subclass":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AbilitySubclass = uint32(in.Uint32())
			}
		case "duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = float32(in.Float32())
			}
		case "has_duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasDuration = bool(in.Bool())
			}
		case "last_applied_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastAppliedTime = float32(in.Float32())
			}
		case "has_last_applied_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasLastAppliedTime = bool(in.Bool())
			}
		case "last_observed_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastObservedTick = uint32(in.Uint32())
			}
		case "subclass":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Subclass = uint32(in.Uint32())
			}
		case "ability":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ability = uint32(in.Uint32())
			}
		case "stack_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StackCount = int32(in.Int32())
			}
		case "start_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTick = uint32(in.Uint32())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis18(out *jwriter.Writer, in RunbackModifier) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.PayloadProto) != 0 {
		const prefix string = ",\"payload_proto\":"
		first = false
		out.RawString(prefix[1:])
		out.Base64Bytes(in.PayloadProto)
	}
	{
		const prefix string = ",\"table_index\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.TableIndex))
	}
	{
		const prefix string = ",\"serial_number\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SerialNumber))
	}
	{
		const prefix string = ",\"has_serial_number\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasSerialNumber))
	}
	{
		const prefix string = ",\"parent\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Parent))
	}
	{
		const prefix string = ",\"caster\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Caster))
	}
	{
		const prefix string = ",\"ability_subclass\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.AbilitySubclass))
	}
	{
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.Float32(float32(in.Duration))
	}
	{
		const prefix string = ",\"has_duration\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasDuration))
	}
	{
		const prefix string = ",\"last_applied_time\":"
		out.RawString(prefix)
		out.Float32(float32(in.LastAppliedTime))
	}
	{
		const prefix string = ",\"has_last_applied_time\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasLastAppliedTime))
	}
	{
		const prefix string = ",\"last_observed_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.LastObservedTick))
	}
	{
		const prefix string = ",\"subclass\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Subclass))
	}
	{
		const prefix string = ",\"ability\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Ability))
	}
	{
		const prefix string = ",\"stack_count\":"
		out.RawString(prefix)
		out.Int32(int32(in.StackCount))
	}
	{
		const prefix string = ",\"start_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.StartTick))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis17(in *jlexer.Lexer, out *RunbackAbility) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subclass_id":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.SubclassID)
		case "slot":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.Slot)
		case "upgrade_info":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.UpgradeInfo)
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "charges":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Charges)
		case "cooldown_start":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.CooldownStart)
		case "charge_recharge_start":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.ChargeRechargeStart)
		case "charge_recharge_end":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.ChargeRechargeEnd)
		case "cooldown_end":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.CooldownEnd)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis17(out *jwriter.Writer, in RunbackAbility) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subclass_id\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.SubclassID)
	}
	{
		const prefix string = ",\"slot\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.Slot)
	}
	{
		const prefix string = ",\"upgrade_info\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.UpgradeInfo)
	}
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"charges\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Charges)
	}
	{
		const prefix string = ",\"cooldown_start\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.CooldownStart)
	}
	{
		const prefix string = ",\"charge_recharge_start\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.ChargeRechargeStart)
	}
	{
		const prefix string = ",\"charge_recharge_end\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.ChargeRechargeEnd)
	}
	{
		const prefix string = ",\"cooldown_end\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.CooldownEnd)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis16(in *jlexer.Lexer, out *RunbackItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subclass_id":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.SubclassID)
		case "slot":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.Slot)
		case "upgrade_info":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.UpgradeInfo)
		case "entity_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityID = int32(in.Int32())
			}
		case "entity_serial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntitySerial = int32(in.Int32())
			}
		case "class_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassName = string(in.String())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		case "charges":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.Charges)
		case "cooldown_start":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.CooldownStart)
		case "charge_recharge_start":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.ChargeRechargeStart)
		case "charge_recharge_end":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.ChargeRechargeEnd)
		case "cooldown_end":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.CooldownEnd)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis16(out *jwriter.Writer, in RunbackItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subclass_id\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.SubclassID)
	}
	{
		const prefix string = ",\"slot\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.Slot)
	}
	{
		const prefix string = ",\"upgrade_info\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.UpgradeInfo)
	}
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"entity_serial\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntitySerial))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	{
		const prefix string = ",\"charges\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.Charges)
	}
	{
		const prefix string = ",\"cooldown_start\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.CooldownStart)
	}
	{
		const prefix string = ",\"charge_recharge_start\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.ChargeRechargeStart)
	}
	{
		const prefix string = ",\"charge_recharge_end\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.ChargeRechargeEnd)
	}
	{
		const prefix string = ",\"cooldown_end\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.CooldownEnd)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in *jlexer.Lexer, out *RunbackUint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = uint32(in.Uint32())
			}
		case "present":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Present = bool(in.Bool())
			}
		case "source_tick":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTick = uint32(in.Uint32())
			}
		case "freshness_ticks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FreshnessTicks = uint32(in.Uint32())
			}
		case "missing_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MissingReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out *jwriter.Writer, in RunbackUint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.Value))
	}
	{
		const prefix string = ",\"present\":"
		out.RawString(prefix)
		out.Bool(bool(in.Present))
	}
	{
		const prefix string = ",\"source_tick\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.SourceTick))
	}
	{
		const prefix string = ",\"freshness_ticks\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.FreshnessTicks))
	}
	if in.MissingReason != "" {
		const prefix string = ",\"missing_reason\":"
		out.RawString(prefix)
		out.String(string(in.MissingReason))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis3(in *jlexer.Lexer, out *RunbackTickProvenance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "tick_interval_seconds":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis12(in, &out.TickIntervalSeconds)
		case "server_start_tick":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis11(in, &out.ServerStartTick)
		case "server_tick":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis15(in, &out.ServerTick)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis3(out *jwriter.Writer, in RunbackTickProvenance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tick_interval_seconds\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis12(out, in.TickIntervalSeconds)
	}
	{
		const prefix string = ",\"server_start_tick\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis11(out, in.ServerStartTick)
	}
	{
		const prefix string = ",\"server_tick\":"
		out.RawString(prefix)
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis15(out, in.ServerTick)
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis2(in *jlexer.Lexer, out *ReplayIdentityCorrespondence) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "expected":
			easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis20(in, &out.Expected)
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = ReplayCorrespondenceStatus(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis2(out *jwriter.Writer, in ReplayIdentityCorrespondence) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"expected\":"
		out.RawString(prefix[1:])
		easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis20(out, in.Expected)
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Reason != "" {
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis20(in *jlexer.Lexer, out *ReplayIdentityExpectation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sha256":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SHA256 = string(in.String())
			}
		case "match_id":
			if in.IsNull() {
				in.Skip()
				out.MatchID = nil
			} else {
				if out.MatchID == nil {
					out.MatchID = new(uint64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MatchID = uint64(in.Uint64())
				}
			}
		case "game":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Game = string(in.String())
			}
		case "map":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Map = string(in.String())
			}
		case "game_build":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GameBuild = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis20(out *jwriter.Writer, in ReplayIdentityExpectation) {
	out.RawByte('{')
	first := true
	_ = first
	if in.SHA256 != "" {
		const prefix string = ",\"sha256\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.SHA256))
	}
	if in.MatchID != nil {
		const prefix string = ",\"match_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(*in.MatchID))
	}
	if in.Game != "" {
		const prefix string = ",\"game\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Game))
	}
	if in.Map != "" {
		const prefix string = ",\"map\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Map))
	}
	if in.GameBuild != 0 {
		const prefix string = ",\"game_build\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.GameBuild))
	}
	out.RawByte('}')
}
func easyjson2e0e899cDecodeGithubComParalinS2replayAnalysis1(in *jlexer.Lexer, out *ReplaySourceIdentity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sha256":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SHA256 = string(in.String())
			}
		case "match_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MatchID = uint64(in.Uint64())
			}
		case "game":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Game = string(in.String())
			}
		case "map":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Map = string(in.String())
			}
		case "game_build":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GameBuild = int32(in.Int32())
			}
		case "parser":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Parser = string(in.String())
			}
		case "parser_revision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParserRevision = string(in.String())
			}
		case "vcs_revision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VCSRevision = string(in.String())
			}
		case "match_id_missing_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MatchIDMissingReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e0e899cEncodeGithubComParalinS2replayAnalysis1(out *jwriter.Writer, in ReplaySourceIdentity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sha256\":"
		out.RawString(prefix[1:])
		out.String(string(in.SHA256))
	}
	{
		const prefix string = ",\"match_id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.MatchID))
	}
	{
		const prefix string = ",\"game\":"
		out.RawString(prefix)
		out.String(string(in.Game))
	}
	{
		const prefix string = ",\"map\":"
		out.RawString(prefix)
		out.String(string(in.Map))
	}
	{
		const prefix string = ",\"game_build\":"
		out.RawString(prefix)
		out.Int32(int32(in.GameBuild))
	}
	{
		const prefix string = ",\"parser\":"
		out.RawString(prefix)
		out.String(string(in.Parser))
	}
	{
		const prefix string = ",\"parser_revision\":"
		out.RawString(prefix)
		out.String(string(in.ParserRevision))
	}
	if in.VCSRevision != "" {
		const prefix string = ",\"vcs_revision\":"
		out.RawString(prefix)
		out.String(string(in.VCSRevision))
	}
	if in.MatchIDMissingReason != "" {
		const prefix string = ",\"match_id_missing_reason\":"
		out.RawString(prefix)
		out.String(string(in.MatchIDMissingReason))
	}
	out.RawByte('}')
}
